### ISSUE TITLE
What's wrong with me?

### ISSUE THREAD

**Issue by LZMHIT** [USC-ACTLab/crazyswarm#101]
I  use Ubuntu 14.04 and When I run .build.sh, There exists some errors  
/usr/bin/ld: cannot find -lBoost::system
/usr/bin/ld: cannot find -lBoost::thread

**Comment by whoenig** [comment]
We test and support Ubuntu 16.04 only, at the moment. However, 14.04 "should" work in theory - did you install libboost-dev?
