### ISSUE TITLE
Crazyradio firmware update and chooser. py timeout error

### ISSUE THREAD

**Issue by astridtepie** [USC-ACTLab/crazyswarm#104]
Hello,
I am actually working on the crazyswarm tutorial, I can't launch the hover_swarm file and I always get timeout error on the chooser.py server. I could update successfully my crazyflie but for one reason or another the firmware update of the crazyradio is not successful. The errors I have are shown on the pictures below, does any one have any clue on what should be done to get pass this problem?
Thanks in advance!
![chooser-python](https://user-images.githubusercontent.com/43744147/46756574-15703200-ccc8-11e8-9f4c-1fe19bd2c49a.png)
![crazyradio-bootload](https://user-images.githubusercontent.com/43744147/46756575-1608c880-ccc8-11e8-90ff-013ae629f917.png)

**Comment by whoenig** [comment]
For the first error: It can't find the Crazyradio - did you set the udev rules?

For the second issue: you specify a folder, but you need to specify a file instead. ("python crazyradio-firmware/usbtools/nrfbootload.py flash prebuilt/cradio.bin").

**Comment by astridtepie** [comment]
Yes I did set the udev rule and when I run the command with the specific file, the following error pop up.
![cradiobin](https://user-images.githubusercontent.com/43744147/46867394-19659680-ce25-11e8-9c09-c19d95e60f07.png)
![udev](https://user-images.githubusercontent.com/43744147/46867399-1d91b400-ce25-11e8-9337-33789359d4a8.png)

**Comment by whoenig** [comment]
You will need to use python instead of python3 (and install any dependencies that you might be missing for python2).

Is your current user account part of the plugdev group (type `groups` on the shell)?

**Comment by astridtepie** [comment]
Yes I am, actually I can now visualize the cf on rviz, I just hqd to chqnge the parameters of the cf on the file. Thanks a lot for your help sir!
