### ISSUE TITLE
crazyswarm LPS issue

### ISSUE THREAD

**Issue by podnerogato** [USC-ACTLab/crazyswarm#113]
Hi, 
I am using ROS kinetic on Ubuntu 16.04, 5 crazyflies, LPS and latest CFClient and Crazyswarm repositories. I have followed your crazyswarm instructions and everything went well. Updated all the firmwares (both CF firmwares, CF radio and LPS) with no problems. I had the addresses set up, and scripts modified as suggested. Chooser.py is functioning as well. I can't get TDoA3 to work. At first i could change mode to TDoA3 using CFClient but the position of the crazyflies would have drifted into hard-coded limits(100,100,100). Then i have updated LPS nodes firmware once again and had setup redone. Now I can't even switch to TDoA3 because all the anchors are red. TWR and TDoA2 are functioning and returning the right position. I execute `source ros_ws/devel/setup.bash
roslaunch crazyswarm hover_swarm.launch` with no errors and rviz starts but I get empty space without crazyflies. Rviz closes with no errors. When i execute "start" on xbox360 controller crazyflies just flip uncontrollably. All the crazyflie were facing +X direction, as suggested. 
I hope I'm at the right address with this question.
Thanks!

EDIT: Using kalman estimator (instead of KalmanUSC), TDoA2 and modifying initial position I have managed to achieve take off and position hold in X and Y, but the Z coordinate from allCrazyflies.yaml is not achieved. When I use KalmanUSC and TDoA2 everything just goes crazy and crashes.

**Comment by podnerogato** [comment]
Thank you for your answer.
I'll give you a bit more info about the problem. All anchors are green in TWR and TDoA2 (as shown on images below). When I select current mode and click Change mode to TDoA3 all anchors remain green in current mode except for anchor 2 that blinks red for a second but turns to green immediately. In some other cases anchors in current mode turn red. Anchors in TDoA3 never turn green and position always drifts to hardcoded limits. Positioning and switching (between) in TWR and TDoA2 works fine. Thanks!
![tdoa2_crop](https://user-images.githubusercontent.com/44773212/48051848-295f6480-e19e-11e8-8324-6f12222dc369.png)
![twr_crop](https://user-images.githubusercontent.com/44773212/48051853-2f554580-e19e-11e8-99d3-adc07eb6cf37.png)

**Comment by whoenig** [comment]
Yes, figure8 should work with LPS. The error message indicates that there was an issue during installation. Does `./build.sh` run through without errors?

**Comment by whoenig** [comment]
Errors might be hard to spot, in particular, if [these](https://github.com/USC-ACTLab/crazyswarm/blob/master/build.sh#L35-L37) lines fail, that would explain your issue. Also, make sure that "python" actually refers to python2 and not python3 (which should be the default for Ubuntu 16.04).
