### ISSUE TITLE
Problems With Multi-flies

### ISSUE THREAD

**Issue by LZMHIT** [USC-ACTLab/crazyswarm#116]
We encountered some problems when flying multiple crazyflies. When the number of crazyflies exceeded three, one crazyflie would fly uncontrolled. Could you tell us how high is the motion capture system you use and the size and mass of the reflective ball attached to the crazyflie.

**Comment by whoenig** [comment]
We use a VICON motion capture system where each reflective marker is at least 3 pixels in size. We use 7.9mm markers (see https://crazyswarm.readthedocs.io/en/latest/hardware.html#components for a link).
