### ISSUE TITLE
Tracking additional objects using the object tracker

### ISSUE THREAD

**Issue by The-SS** [USC-ACTLab/crazyswarm#119]
Hi,

I am working on some applications that require tracking additional objects. Essentially, have two machines and I want each one to control a set of crazyflies, but I want both to track all crazyflies. For example, pc1 would control cf1 and cf2 and pc2 would control cf3 and cf4, but pc1 and pc2 would each track all four cfs.  

Is there anything implemented that would allow for this additional object tracking? (I noticed there is an `object_tracker.yaml` file in `ros_ws/src/crazyswarm/launch`, but it is not being used anywhere).

If, at this point, there is nothing implemented, would it be easier to modify `crazyswarm_server.cpp` or to use one ROS master on both machines and have each machine publish the location of its agents?

Thank you.

**Comment by whoenig** [comment]
If you can use the object tracking mode of your motion capture system, this will work without any issues. Essentially, you can run another node that also connects to the the mocap (e.g., vicon_bridge for vicon). If you have more drones and you want to use our objecttracker, there is currently no such option. I guess in terms of programming, it would require some kind of "fake" Crazyflie.

**Comment by The-SS** [comment]
I'll work on it and update this thread.
Thank you.

**Comment by williamdwarke** [comment]
Any news on this? I actually wrote up an object tracker node using your libobjecttracker that does just this, and even pulls everything for additional robots from the same parameter files.

**Comment by The-SS** [comment]
I haven't worked on this since my last commit. I was thinking I would set up a ROS master over several computers and have each one receive the full point cloud and publish the pose of its agents. 

Could you share your object tracker node? I might use it instead.

**Comment by williamdwarke** [comment]
Sure thing, let me clean it up a little bit and send it to you later this week. It basically just subscribes to the point cloud published by crazyswarm_server and uses libobjectracker in the same way to get and publish the pose of the requested set of agents in the yaml file. So, you could run it on separate machines with separate yaml files as long as you have crazyswarm_server running somewhere on the network.

**Comment by bconvens** [comment]
@williamdwarke could you please share this code with me too? Could you also point me to what you added to the code to achieve this?
I would like to track non-cf objects (e.g. wand, moving obstacles) too using the libobjecttracker. Preferably more than 1 object and without requiring to use fake cfs.
If I understand correctly your code gives this functionality?

Assuming I am able to track positions and yaw of non-cf objects, does anybody know how to send the positions and yaw of all these tracked objects to the crazyflies (together with the vicon position update)? All suggestions are welcome. :-)
Thank you!

**Comment by jpreiss** [comment]
@williamdwarke did you ever clean up this code enough to contribute it back to Crazyswarm? If not, I will close this.

**Comment by williamdwarke** [comment]
No, I moved on to using rigid bodies via vrpn because the ICP tracking was
too unstable for my purposes.

Regards,
William

**Comment by jpreiss** [comment]
OK, thanks for replying.
