### ISSUE TITLE
Problem with chooser.py

### ISSUE THREAD

**Issue by Mic542** [USC-ACTLab/crazyswarm#120]
Hello, guys.
I am new at this crazyswarm.
So I am trying to flash the cf2.0 using the chooser.py but it always failed here is the screenshot:
![image](https://user-images.githubusercontent.com/15632939/48826644-34c1ab00-edae-11e8-9bfe-8fe7bfd2a645.png)
I already flash the radio using the pre-built as the documentation said.

and this is the result of crazyflies_tools scan:
![image](https://user-images.githubusercontent.com/15632939/48826964-32138580-edaf-11e8-9c73-f810fcdb47da.png)

and this is my cf connected using cfclient at the same address E7E7E7E7E7.
![image](https://user-images.githubusercontent.com/15632939/48826721-78b4b000-edae-11e8-85e0-e6ea75d47ac9.png)

Everything i try in chooser.py return timeout and when I try hover_swamp.launch the crazyswamp_server terminated with reason timeout.
Please help me solve this problem..

Thank you in advance.

Edit: I don't think this is related but when I flashed my cf using firmware from this repository and I connect my cf using cfclient, place my cf2 on flat surface then tilt it upside down, the cf then will automatically reboot with red led blinking fast. However when i flashed my cf using firmware from bitcraze's repository this doesn't happen.

**Comment by glennliu** [comment]
Hi 

I met similar problems at the beginning and solved it by checking these,
1. check file `allCrazyflies.yaml` and `crazyflies.yaml`. Make sure the radio channel is correct.
2. check crazyradio device permission is opened. As you can use "scan" function, I think you already achieved this one.

BW

**Comment by Mic542** [comment]
Hi,

this is my crazyflies.yaml:
![image](https://user-images.githubusercontent.com/15632939/48829241-29be4900-edb5-11e8-9ef7-e942da9d88d5.png)
The channel is already at 80.

and this is my allCrazyflies.yaml:
![image](https://user-images.githubusercontent.com/15632939/48829430-8457a500-edb5-11e8-8c01-f0e713ee6b28.png)
it is also with channel 80.

**Comment by glennliu** [comment]
Hi 

Can you try these?
```
channel: 100
id:1
bandwidth: 2M
```
In using cfclient, you drone is connected correctly?

**Comment by Mic542** [comment]
![image](https://user-images.githubusercontent.com/15632939/48830702-8ec76e00-edb8-11e8-99e6-03bd58857c9d.png)
![image](https://user-images.githubusercontent.com/15632939/48830996-35ac0a00-edb9-11e8-9316-7c01d3d87a68.png)
Is that right way to do it?
and I still failed when I try to flash it using chooser.py.
Still the same error, here is the screenshot:
![image](https://user-images.githubusercontent.com/15632939/48830901-04cbd500-edb9-11e8-8be0-f2d361380813.png)

**Comment by glennliu** [comment]
Have you write the changed data into crazyflie? 
You can connect you cf through cfclient and write in channel and bandwidth you just changed. It should be able to work once your drone config and your .yaml are synced.
![screenshot from 2018-11-21 20-04-18](https://user-images.githubusercontent.com/8009679/48840194-ed94e380-edc8-11e8-8cda-871518625a54.png)

**Comment by Mic542** [comment]
Hi.
As you can see here:
![image](https://user-images.githubusercontent.com/15632939/48840552-5896e800-edd2-11e8-9638-c5b51b5a6f2a.png)

My cfclient that I have doesn't have any menu other than flight control.
Where can I get that?

Thank you very much for your response anyways.

**Comment by glennliu** [comment]
I launched my cfclient via `sudo ./bin/cfclient`. You may also try that.
As you can see on your cfclient upper left, you are in channel:80 and bandwidth:250K. This is your currently real setting for radio, which is been wrote into your EEPROM on drone. **You need to change the setting and rewrote into drone.**
It can be changed through upper menu /connect/Configure 2.0, which you can see on my previous screenshot.

**Comment by Mic542** [comment]
So you are using the one inside bin folder that come with this repository, right?
Maybe I need to launch it with sudo.
My cfclient right now does not have upper menu though.
Well, I will try it as you said tomorrow. I will post the update of this too.

Hopefully this can solve my problem too.

As always thank you very much.

**Comment by glennliu** [comment]
yep, I launch it with in sudo. I'm not sure is it right. But it work very well in my PC.

**Comment by whoenig** [comment]
Great to see users helping each other:-) If you need sudo, that likely means that you didn't deploy the udev-rules for the Crazyradio.

**Comment by Mic542** [comment]
After I did it like @glennliu has said. Yes! I can flash it from chooser.py. However there is this timeout that keep appearing after sometimes.
![image](https://user-images.githubusercontent.com/15632939/48874887-0b9a2c80-ee39-11e8-9e44-6f1542c1d6a5.png)
As the above image, I was able to get the battery and version but after that everything I clicked resulted in time out or just empty. 

Anyways thank you very much @glennliu at least I can flash it using chooser.

**Comment by glennliu** [comment]
You can try look ros_drivers folder: https://github.com/whoenig/crazyflie_tools/tree/0662e65b60b7577ca7fbb8118d687ba2ca679bda/src

At each file(battery.cpp, reboot.cpp), change its radio parameters to your radio setting. And it should be worked after that.

**Comment by Mic542** [comment]
Even after doing that I still get timeout every so often and i need to re plug my radio to make it work again.

**Comment by Mic542** [comment]
It seem this issue is resolved. As @glennliu said I need to launch cfclient from bin folder using sudo command, change the address of the cf, and the chooser.py worked. it just every so often the timeout occured and I just need to unplug and plug the radio again. Closing this issue.
