### ISSUE TITLE
testCrazyflieSim.py error

### ISSUE THREAD

**Issue by dontbeafraidimnotagoodman** [USC-ACTLab/crazyswarm#128]
Hi, 
First of all thanks for building this package for crazyflie.
I am randomly trying to find something to simulate multiple crazyflie when I found testCrazyflie.py, I got this error
 
coven-lab@coven-lab:~/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm$ python testCrazyflieSim.py
Traceback (most recent call last):
  File "testCrazyflieSim.py", line 4, in <module>
    from cfsim import CrazyflieSim, TimeHelper
ImportError: cannot import name CrazyflieSim

Is there any script I could change to make this one work?

Thanks again

**Comment by whoenig** [comment]
This file is probably simply outdated and should also not be needed for normal operation. You can run any script in simulation by appending the `--sim` command argument. There is an example here: https://crazyswarm.readthedocs.io/en/latest/installation.html#simulation-only.
