### ISSUE TITLE
Adding battery/voltage Param

### ISSUE THREAD

**Issue by zserlin** [USC-ACTLab/crazyswarm#133]
I would like to get the battery voltage of each cf as a param (i.e. /cf4/battery/voltage). I see that battery voltage is in crazyflie_ros, I just cant figure out how to get it to run in crazyswarm. Any help would be much appreciated!

**Comment by whoenig** [comment]
You could enable logging in the crazyswarm and then configure it as a logging variable. However, this approach will reduce the number of CFs you can control per radio. The variable is called "pm.vbat". You can configure logging variables here: https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L19, enable logging here: https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L54, and receive the results in the ros topic "/cf<id>/log1".
