### ISSUE TITLE
Problem with excluding external dependencies while compiling build.sh file

### ISSUE THREAD

**Issue by AhmedA92** [USC-ACTLab/crazyswarm#138]
Hello everyone,
It is very basic question I know, I can't compile the build.sh script in crazyswarm folder as I get this error everytime:

> CMake Error at externalDependencies/libmotioncapture/CMakeLists.txt:118 (find_package):
  By not providing "FindVRPN.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VRPN", but
  CMake did not find one.
 Could not find a package configuration file provided by "VRPN" with any of
  the following names:
    VRPNConfig.cmake
    vrpn-config.cmake
  Add the installation prefix of "VRPN" to CMAKE_PREFIX_PATH or set
  "VRPN_DIR" to a directory containing one of the above files.  If "VRPN"
  provides a separate development package or SDK, be sure it has been
  installed.

As I will be using LPS with 8 anchors, I don't need Vicon so I dont want to compile any code for these external systems.

Thanks!

**Comment by hanzheteng** [comment]
Please see issue #129

**Comment by AhmedA92** [comment]
Thank you!
