### ISSUE TITLE
How to use phase space as the mocap system

### ISSUE THREAD

**Issue by zehuilu** [USC-ACTLab/crazyswarm#159]
Hi guys,

I want to use phase space as the motion capture system. I know I need to enable the phase space in libmotioncapture/CMakeLists.txt. But I don't know what I should put into libmotioncapture/externalDependencies/ and what else I should do after I revise the launch file. Should I put an official SDK in externalDependencies or a ROS package for phase space?

I will appreciate your help very much!

**Comment by whoenig** [comment]
It should be the official C++ SDK for phasespace. Note that when we tested it last, we just had some Beta version of the SDK, so things might have changed in the meantime.

**Comment by zehuilu** [comment]
@whoenig Thanks for the reply! I will let you know if we have anything updated.

**Comment by jpreiss** [comment]
@zehuilu were you able to resolve this?

**Comment by zehuilu** [comment]
@jpreiss Hi James, I wasn't able to resolve this problem. I switched to other types of quadrotors and built my controller. Feel free to close this issue :)

**Comment by jpreiss** [comment]
Thanks for replying!
