### ISSUE TITLE
Confusion about log TOC variables

### ISSUE THREAD

**Issue by cf11111** [USC-ACTLab/crazyswarm#163]
Sorry to start a new thread on this, I tried to look it up in other threads but am still confused by the variables in the logTOC.  I have the latest CF firmware.

1. Are the stateEstimate.roll, pitch, and yaw the rate values (deg/s)?  

2. Also I understand that these stateEstimate values incorporate mocap data into the estimation (I am using estimator 3 fyi) -- is there a way to get position and orientation estimates without using mocap data?

I expected to see variables like stabilizer.x, acc.x, and gyro.x available to be logged, but they do not appear in my TOC.

![IMG-3369 (1)](https://user-images.githubusercontent.com/52216462/60271180-dd456980-98bf-11e9-950d-16e10fe52a4c.jpg)

**Comment by cf11111** [comment]
I expected to see variables like acc.x and gyro.x available to be logged, but they do not appear in my TOC.

**Comment by whoenig** [comment]
This does not seem to be related to the Crazyswarm. Please ask in the official support forum (https://forum.bitcraze.io/).
