### ISSUE TITLE
Crazyflie ROS waypoint following

### ISSUE THREAD

**Issue by harrafa** [USC-ACTLab/crazyswarm#164]
I am implementing ROS for waypoint following with aruco tag. 
When I run the controller.cpp at frequency greater than 8Hz, the function transformpose() (to transform world reference points to crazyflie frame) forces the controller node to exit with the error:
 Quaternion malformed, magnitude: 0 should be 1.0
Interestingly, I am able to run the controller at frequencies less than 5Hz.
Could you please take a look at my launch file and controller.cpp for any mistakes I am making. Eagerly awaiting your response.
Thank you.

![Screenshot from 2019-07-16 22-22-27](https://user-images.githubusercontent.com/49574110/61349275-60e7db80-a818-11e9-953e-122e9ac9ee03.png)
![Screenshot from 2019-07-16 22-22-34](https://user-images.githubusercontent.com/49574110/61349278-61807200-a818-11e9-8c3a-e8146ec8bbbd.png)
![Screenshot from 2019-07-16 22-22-38](https://user-images.githubusercontent.com/49574110/61349279-61807200-a818-11e9-8832-5edac1a500b5.png)
![Screenshot from 2019-07-16 22-22-53](https://user-images.githubusercontent.com/49574110/61349280-62190880-a818-11e9-9937-781a4537bd69.png)

**Comment by whoenig** [comment]
You should not use any version of crazyflie_controller. Instead, use the goTo function which uses the onboard attitude and position controller, see https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/scripts/waypoints.py for an example.

**Comment by harrafa** [comment]
Thank you for your timely response. Are you suggesting I install the crayswarm repo instead of crazyflie_ros?

**Comment by whoenig** [comment]
You posted this question on the crazyswarm repository, so I assumed that's what you are using. For crazyflie_ros there is an example on how to use the HL mode here: https://github.com/whoenig/crazyflie_ros/blob/master/crazyflie_demo/scripts/test_high_level.py. You can also publish commands to the cmd_position topics instead in order to use the on-board position controller.

**Comment by harrafa** [comment]
I am sorry. I will take it off from here.
