### ISSUE TITLE
random timeout Error on upload_trajectory

### ISSUE THREAD

**Issue by sadransh** [USC-ACTLab/crazyswarm#172]
I randomly get such error when trying to run demo with multiple crazyflies. Some times with trying to re run the command (python figure8_csv.py) drones start flying.
 Do you have guess what may cause this happen? and how can I solve it?  the timeout happens sometimes on cf4 and randomly changes to cf3.

![image](https://user-images.githubusercontent.com/12527824/67047500-094b5b80-f0f8-11e9-8bb2-457b6dd1b31f.png)

**OS :** Ubuntu 16.04 
**System :** 
- crazyflies and radio are updated to latest master commit.

- working on VRPN based system the cameras are Motion Analysis. 

**Warnings recieved :**

- I get warning "No updated pose for motion capture object %s". I think the reason is different data structure which Motion Analysis software is sending. 

- sometimes get high latency warning (very rare)

**Comment by whoenig** [comment]
Can you please try changing https://github.com/whoenig/crazyflie_cpp/blob/master/src/Crazyflie.cpp#L1268 to `if (false) {`? Then recompile using `catkin_make` in the `ros_ws` folder. I have seen this kind of behavior before too, and I was able to fix it that way. I think it is related to an issue on the firmware side where sometimes packets still get dropped.

The warnings are normal, as long as they don't pop-up constantly.

**Comment by sadransh** [comment]
Haven't seen the error yet. ( with 8 tests ) 
I'll close the issue for now. 
Thanks a lot.

I ll be happy if you show me any possible problems or developements needed on this project that I can work on it.

**Comment by whoenig** [comment]
Thanks for the feedback. PRs are always welcome. Just start using it and I am sure you will run into something that can be improved. Thanks!
