### ISSUE TITLE
test.launch: object_tracker ROS node

### ISSUE THREAD

**Issue by kgslovak** [USC-ACTLab/crazyswarm#20]
Hey Wolfgang,

I'm getting the `std::runtime_error` when using the "hover_swarm" launch-script (which I assume is due to my firmware build being messed up), but while I'm figuring out how to fix it I thought I'd test my Vicon setup. However, when running the `test.launch` script, I encountered the old reference to the `object_tracker` ROS node. Is there a quick fix to sub' in the "libobjecttracker"?

Thanks,
Kyle

**Comment by jpreiss** [comment]
`test.launch` was outdated, removed in 8b76956.
