### ISSUE TITLE
Use lighthouse positioning system

### ISSUE THREAD

**Issue by Rucy-kim** [USC-ACTLab/crazyswarm#205]
Hi

I am trying to test crazyswarm using lighthouse positioning system.

But i don't know how to set the position of base station

I proceeded with the contents of this link and succeeded in acquiring position with the latest firmware of bitcraze.
[https://github.com/bitcraze/crazyflie-firmware/blob/master/docs/functional-areas/lighthouse_overview.md](https://github.com/bitcraze/crazyflie-firmware/blob/master/docs/functional-areas/lighthouse_overview.md)

Do I have to do the same in crazyswarm to use the lighthouse positioning system?

Thank you in advance for any help you can provide!

**Comment by whoenig** [comment]
The same approach should work. Simply use the modified firmware, and make sure that you disable the motion capture (set https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L36 to "none").

**Comment by Rucy-kim** [comment]
That sounds great! Thank you for your reply.
