### ISSUE TITLE
 role of crazyflie-firmware included as a submodule in the crazyswarm

### ISSUE THREAD

**Issue by Rucy-kim** [USC-ACTLab/crazyswarm#210]
Hi!

I have a question.

When I asked about the firmware of the lighthouse position system, I received an answer that bitcraze's official firmware was sufficient.
[https://github.com/USC-ACTLab/crazyswarm/issues/208#issuecomment-623708557](https://github.com/USC-ACTLab/crazyswarm/issues/208#issuecomment-623708557)

So what is the role of crazyflie-firmware included as a submodule in the crazyswarm repository?

**Comment by jpreiss** [comment]
1. Our submodule points to a specific version of the firmware that has been tested and observed to work with Crazyswarm.

2. Our simulator builds selected pieces code from the firmware for x86 with Python bindings generated by SWIG. This is useful for testing.
