### ISSUE TITLE
Need help troubleshooting hover.launch

### ISSUE THREAD

**Issue by jcampbellNP** [USC-ACTLab/crazyswarm#219]
Hello,

I am unable to get the hover.launch script to run and get my CF to fly. I am using an OptriTrack system. The data is streaming from Motive, and I am able to get the mocap_helper.launch to work (it shows my rigid body data from Motive).

When I launch the hover.launch script RVIZ opens but there is nothing inside of it. I am not getting any errors. It just looks like it is not finding the CF.
I have followed all of the directions for the crazyswarm installation, preparation and configuration files. All of the crazyflie addresses are correct with the correct firmware from the directions.

Here is the hover.launch script and the logs for mocap_helper.launch and hover.launch. Any ideas what I should do to get my CF flying?

hover.launch
```
<?xml version="1.0"?>
<launch>
 <arg name="joy_dev" default="/dev/input/js0" />
  <rosparam command="load" file="$(find crazyswarm)/launch/crazyflies.yaml" />
 <rosparam command="load" file="$(find crazyswarm)/launch/crazyflieTypes.yaml" />
  <node pkg="crazyswarm" type="crazyswarm_server" name="crazyswarm_server" output="screen" >
   <rosparam>
     world_frame: "/world"
     # Logging configuration (Use enable_logging to actually enable logging)
     genericLogTopics: ["log1"]
     genericLogTopicFrequencies: [10]
     genericLogTopic_log1_Variables: ["stateEstimate.x", "ctrltarget.x"]
     # firmware parameters for all drones (use crazyflieTypes.yaml to set per type, or
     # allCrazyflies.yaml to set per drone)
     firmwareParams:
       commander:
         enHighLevel: 1
       stabilizer:
         estimator: 2 # 1: complementary, 2: kalman
         controller: 2 # 1: PID, 2: mellinger
       ring:
         effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
         solidBlue: 255 # if set to solid color
         solidGreen: 0 # if set to solid color
         solidRed: 0 # if set to solid color
         headlightEnable: 0
       locSrv:
         extPosStdDev: 1e-3
         extQuatStdDev: 0.5e-1
       kalman:
         pNAcc_xy: 1.0
         pNAcc_z: 2.0
     # tracking
     motion_capture_type: "optitrack" # one of none,vicon,optitrack,qualisys,vrpn
     object_tracking_type: "motionCapture" # one of motionCapture,libobjecttracker
     send_position_only: False # set to False to send position+orientation; set to True to send position only
     # vicon_host_name: "vicon"
     # optitrack_host_name: "optitrack"
     optitrack_local_ip: "***.***.***.***"
     optitrack_server_ip: "***.***.***.***"
     # qualisys_host_name: "10.0.5.219"
     # qualisys_base_port: 22222
     # vrpn_host_name: "vicon"
     save_point_clouds: ~/pointCloud.ot
     print_latency: False
     write_csvs: False
     force_no_cache: False
     enable_parameters: True
     enable_logging: True
   </rosparam>
 </node>
 
 <!-- <node name="joy" pkg="joy" type="joy_node" output="screen">-->
 <!--   <param name="dev" value="$(arg joy_dev)" />-->
 <!-- </node>-->
 
 <node pkg="crazyswarm" type="crazyswarm_teleop" name="crazyswarm_teleop" output="screen">
   <param name="csv_file" value="$(find crazyswarm)/launch/figure8_smooth.csv" />
   <param name="timescale" value="0.8" />
 </node>
 
 <node name="rviz" pkg="rviz" type="rviz" args="-d $(find crazyswarm)/launch/test.rviz"/>
 
 <!-- <node pkg="rqt_plot" type="rqt_plot" name="rqt_plot_x" args="/cf2/log1/values[0]"/> -->
 <!-- <node pkg="rqt_plot" type="rqt_plot" name="rqt_plot_roll" args="/cf1/log1/values[2] /cf1/log1/values[3]"/> -->
 
</launch>
 ```
 

SUMMARY
========

PARAMETERS
 * /mocap_helper/motion_capture_type: optitrack
 * /mocap_helper/object_tracking_type: motionCapture
 * /mocap_helper/optitrack_host_name: optitrack
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /
	mocap_helper (crazyswarm/mocap_helper)

ROS_MASTER_URI=http://localhost:11311

process[mocap_helper-1]: started with pid [30317]
frame 0:
	points:
	objects:
  	"cf1":
     	occluded: 0
     	position: [-4.92317, 0.570461, 0.822788]
     	rotation: [-0.788251, 0.104755, -0.11158, 0.596017]
frame 1:
	points:
	objects:
  	"cf1":
     	occluded: 0
     	position: [-4.92333, 0.570375, 0.822856]
     	rotation: [-0.78732, 0.10543, -0.111544, 0.597135]
frame 2:
	points:
	objects:
  	"cf1":
     	occluded: 0
     	position: [-4.92335, 0.570372, 0.822874]
     	rotation: [-0.787303, 0.105194, -0.111712, 0.597167]
frame 3:
	points:
	objects:
  	"cf1":
     	occluded: 0
     	position: [-4.92329, 0.570315, 0.822843]
     	rotation: [-0.787619, 0.105473, -0.110191, 0.596984]

hover.launch

SUMMARY
========

PARAMETERS
 * /crazyflieTypes/default/batteryVoltageWarning: 3.8
 * /crazyflieTypes/default/batteryVoltateCritical: 3.7
 * /crazyflieTypes/default/bigQuad: False
 * /crazyflieTypes/default/dynamicsConfiguration: 0
 * /crazyflieTypes/default/firmwareParams/ctrlMel/i_range_m_z: 1500
 * /crazyflieTypes/default/firmwareParams/ctrlMel/i_range_xy: 2.0
 * /crazyflieTypes/default/firmwareParams/ctrlMel/i_range_z: 0.4
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kR_xy: 70000
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kR_z: 60000
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kd_omega_rp: 200
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kd_xy: 0.2
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kd_z: 0.4
 * /crazyflieTypes/default/firmwareParams/ctrlMel/ki_m_z: 500
 * /crazyflieTypes/default/firmwareParams/ctrlMel/ki_xy: 0.05
 * /crazyflieTypes/default/firmwareParams/ctrlMel/ki_z: 0.05
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kp_xy: 0.4
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kp_z: 1.25
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kw_xy: 20000
 * /crazyflieTypes/default/firmwareParams/ctrlMel/kw_z: 12000
 * /crazyflieTypes/default/firmwareParams/ctrlMel/mass: 0.032
 * /crazyflieTypes/default/firmwareParams/ctrlMel/massThrust: 132000
 * /crazyflieTypes/default/markerConfiguration: 0
 * /crazyflieTypes/defaultSingleMarker/batteryVoltageWarning: 3.8
 * /crazyflieTypes/defaultSingleMarker/batteryVoltateCritical: 3.7
 * /crazyflieTypes/defaultSingleMarker/bigQuad: False
 * /crazyflieTypes/defaultSingleMarker/dynamicsConfiguration: 0
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/i_range_m_z: 1500
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/i_range_xy: 2.0
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/i_range_z: 0.4
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kR_xy: 70000
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kR_z: 60000
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kd_omega_rp: 200
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kd_xy: 0.2
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kd_z: 0.4
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/ki_m_z: 500
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/ki_xy: 0.05
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/ki_z: 0.05
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kp_xy: 0.4
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kp_z: 1.25
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kw_xy: 20000
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/kw_z: 12000
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/mass: 0.032
 * /crazyflieTypes/defaultSingleMarker/firmwareParams/ctrlMel/massThrust: 132000
 * /crazyflieTypes/defaultSingleMarker/markerConfiguration: 3
 * /crazyflieTypes/large/batteryVoltageWarning: 11.4
 * /crazyflieTypes/large/batteryVoltateCritical: 11.1
 * /crazyflieTypes/large/bigQuad: True
 * /crazyflieTypes/large/dynamicsConfiguration: 0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/i_range_m_z: 1500
 * /crazyflieTypes/large/firmwareParams/ctrlMel/i_range_xy: 2.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/i_range_z: 4.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kR_xy: 30000
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kR_z: 40000
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kd_omega_rp: 100
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kd_xy: 3.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kd_z: 3.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/ki_m_z: 500
 * /crazyflieTypes/large/firmwareParams/ctrlMel/ki_xy: 1.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/ki_z: 2.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kp_xy: 8.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kp_z: 8.0
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kw_xy: 9000
 * /crazyflieTypes/large/firmwareParams/ctrlMel/kw_z: 10000
 * /crazyflieTypes/large/firmwareParams/ctrlMel/mass: 0.38
 * /crazyflieTypes/large/firmwareParams/ctrlMel/massThrust: 5400
 * /crazyflieTypes/large/markerConfiguration: 2
 * /crazyflieTypes/medium/batteryVoltageWarning: 7.6
 * /crazyflieTypes/medium/batteryVoltateCritical: 7.4
 * /crazyflieTypes/medium/bigQuad: True
 * /crazyflieTypes/medium/dynamicsConfiguration: 0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/i_range_m_z: 1500
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/i_range_xy: 2.0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/i_range_z: 2.0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kR_xy: 50000
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kR_z: 60000
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kd_omega_rp: 200
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kd_xy: 1.0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kd_z: 1.0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/ki_m_z: 500
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/ki_xy: 0.1
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/ki_z: 0.5
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kp_xy: 2.0
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kp_z: 3
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kw_xy: 16000
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/kw_z: 12000
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/mass: 0.11
 * /crazyflieTypes/medium/firmwareParams/ctrlMel/massThrust: 23000
 * /crazyflieTypes/medium/markerConfiguration: 1
 * /crazyflies: [{'initialPositio...
 * /crazyswarm_server/enable_logging: True
 * /crazyswarm_server/enable_parameters: True
 * /crazyswarm_server/firmwareParams/commander/enHighLevel: 1
 * /crazyswarm_server/firmwareParams/kalman/pNAcc_xy: 1.0
 * /crazyswarm_server/firmwareParams/kalman/pNAcc_z: 2.0
 * /crazyswarm_server/firmwareParams/locSrv/extPosStdDev: 1e-3
 * /crazyswarm_server/firmwareParams/locSrv/extQuatStdDev: 0.05
 * /crazyswarm_server/firmwareParams/ring/effect: 16
 * /crazyswarm_server/firmwareParams/ring/headlightEnable: 0
 * /crazyswarm_server/firmwareParams/ring/solidBlue: 255
 * /crazyswarm_server/firmwareParams/ring/solidGreen: 0
 * /crazyswarm_server/firmwareParams/ring/solidRed: 0
 * /crazyswarm_server/firmwareParams/stabilizer/controller: 2
 * /crazyswarm_server/firmwareParams/stabilizer/estimator: 2
 * /crazyswarm_server/force_no_cache: False
 * /crazyswarm_server/genericLogTopicFrequencies: [10]
 * /crazyswarm_server/genericLogTopic_log1_Variables: ['stateEstimate.x...
 * /crazyswarm_server/genericLogTopics: ['log1']
 * /crazyswarm_server/motion_capture_type: optitrack
 * /crazyswarm_server/object_tracking_type: motionCapture
 * /crazyswarm_server/optitrack_local_ip: 10.0.13.177
 * /crazyswarm_server/optitrack_server_ip: 10.0.13.184
 * /crazyswarm_server/print_latency: False
 * /crazyswarm_server/save_point_clouds: ~/pointCloud.ot
 * /crazyswarm_server/send_position_only: False
 * /crazyswarm_server/world_frame: /world
 * /crazyswarm_server/write_csvs: False
 * /crazyswarm_teleop/csv_file: /home/jcampbell/c...
 * /crazyswarm_teleop/timescale: 0.8
 * /dynamicsConfigurations/0/maxFitnessScore: 0.001
 * /dynamicsConfigurations/0/maxPitch: 1.4
 * /dynamicsConfigurations/0/maxPitchRate: 20.0
 * /dynamicsConfigurations/0/maxRoll: 1.4
 * /dynamicsConfigurations/0/maxRollRate: 20.0
 * /dynamicsConfigurations/0/maxXVelocity: 2.0
 * /dynamicsConfigurations/0/maxYVelocity: 2.0
 * /dynamicsConfigurations/0/maxYawRate: 10.0
 * /dynamicsConfigurations/0/maxZVelocity: 3.0
 * /markerConfigurations/0/numPoints: 4
 * /markerConfigurations/0/offset: [0.0, -0.01, -0.04]
 * /markerConfigurations/0/points/0: [0.0307946, -0.00...
 * /markerConfigurations/0/points/1: [0.0690987, -0.06...
 * /markerConfigurations/0/points/2: [0.0680017, 0.005...
 * /markerConfigurations/0/points/3: [-0.00648208, -0....
 * /markerConfigurations/1/numPoints: 4
 * /markerConfigurations/1/offset: [0.0, 0.0, -0.03]
 * /markerConfigurations/1/points/0: [-0.00896228, -0....
 * /markerConfigurations/1/points/1: [-0.0156318, 0.09...
 * /markerConfigurations/1/points/2: [0.0461693, -0.08...
 * /markerConfigurations/1/points/3: [-0.0789959, -0.0...
 * /markerConfigurations/2/numPoints: 4
 * /markerConfigurations/2/offset: [0.0, 0.0, -0.06]
 * /markerConfigurations/2/points/0: [0.0558163, -0.00...
 * /markerConfigurations/2/points/1: [-0.0113941, 0.00...
 * /markerConfigurations/2/points/2: [-0.0306277, 0.05...
 * /markerConfigurations/2/points/3: [0.0535816, -0.04...
 * /markerConfigurations/3/numPoints: 1
 * /markerConfigurations/3/offset: [0.0, -0.01, -0.04]
 * /markerConfigurations/3/points/0: [0.0177184, 0.013...
 * /numDynamicsConfigurations: 1
 * /numMarkerConfigurations: 4
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /
	crazyswarm_server (crazyswarm/crazyswarm_server)
	crazyswarm_teleop (crazyswarm/crazyswarm_teleop)
	rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [30030]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 40d252aa-ac0c-11ea-8e0d-64006a91f7f5
process[rosout-1]: started with pid [30041]
started core service [/rosout]
process[crazyswarm_server-2]: started with pid [30048]
process[crazyswarm_teleop-3]: started with pid [30049]
process[rviz-4]: started with pid [30054]
[ INFO] [1591897922.605681352]: Wait for services...
[ INFO] [1591897922.607034106]: waitForService: Service [/emergency] has not been advertised, waiting...
[ INFO] [1591897922.689557690]: waitForService: Service [/emergency] is now available.
[ INFO] [1591897922.691725150]: Manager ready.

**Comment by jpreiss** [comment]
Does your `crazyflies.yaml` show your crazyflie with id `1` and the correct radio channel?

Another common culprit when using the mocap's object tracking is not giving the objects names like `cf1, cf2, ...` but it looks like you did that.

You are using ROS melodic and presumably Ubuntu 18.04, whereas we only support ROS kinetic on Ubuntu 16.04. However, if everything compiled correctly, I think it should work.

**Comment by whoenig** [comment]
I use it with 18.04/Melodic and this works fine for me. Please share your `crazyflies.yaml`.

**Comment by jpreiss** [comment]
Should we update the docs to show support for 18.04/melodic?

**Comment by jcampbellNP** [comment]
Thank you for your responses .I have the address for my CF as 0/80/2M/E7E7E7E701
Here is the crazyflies.yaml. 
crazyflies:
  - id: 1
    channel: 80
    initialPosition: [0.0,0.0, 0.0]
    type: default
  - id: 2
    channel: 80
    initialPosition: [0.0,0.0, 0.0]
    type: default

**Comment by whoenig** [comment]
This kind of process stall means that there is trouble with connecting to OptiTrack. From the logs, it seems `mocap_helper.launch` actually uses a different configuration (hostname: "optitrack" vs "10.0.13.184"). Also, double check your launch file. If you are on the latest version, the configuration parameter should be "optitrack_host_name", see https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/src/crazyswarm_server.cpp#L1443-L1449 and https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L40. The parameters you set are not used in the latest version. If you used the Crazyswarm for a long time, make sure that you update all submodules, since the optitrack support improved dramatically about a year ago.

**Comment by whoenig** [comment]
@jpreiss I just pushed a change to include 18.04 in the list of supported OS.

**Comment by jpreiss** [comment]
@jcampbellNP the `crazyflies.yaml` should only contain the CFs that you are actively using. The intended workflow is to list all of the CFs you own in `allCrazyflies.yaml`, then use `chooser.py` to graphically select the subset that you want to use. `chooser.py` overwrites `crazyflies.yaml`.

**Comment by jcampbellNP** [comment]
Thank you both for all of your help. It came down to setting "optitrack_host_name" to the correct host IP address and making sure that the crazyflies.yaml was also correct.

**Comment by jpreiss** [comment]
Glad to hear it's working for you now!
