### ISSUE TITLE
launch hover swarm timeout error

### ISSUE THREAD

**Issue by glennliu** [USC-ACTLab/crazyswarm#22]
Hi 

I was trying to launch hover_swarm.launch, with timeout() error showed in terminal,

> SUMMARY
> ========
> 
> PARAMETERS
>  * /crazyflie_manager/csv_file: /home/xiaohao/bit...
>  * /crazyflie_manager/timescale: 0.8
>  * /crazyflie_server/broadcast_uri: radio://0/100/2M/...
>  * /crazyflie_server/dynamicsConfigurations/0/maxFitnessScore: 0.001
>  * /crazyflie_server/dynamicsConfigurations/0/maxPitch: 1.4
>  * /crazyflie_server/dynamicsConfigurations/0/maxPitchRate: 20.0
>  * /crazyflie_server/dynamicsConfigurations/0/maxRoll: 1.4
>  * /crazyflie_server/dynamicsConfigurations/0/maxRollRate: 20.0
>  * /crazyflie_server/dynamicsConfigurations/0/maxXVelocity: 2.0
>  * /crazyflie_server/dynamicsConfigurations/0/maxYVelocity: 2.0
>  * /crazyflie_server/dynamicsConfigurations/0/maxYawRate: 10.0
>  * /crazyflie_server/dynamicsConfigurations/0/maxZVelocity: 3.0
>  * /crazyflie_server/enable_logging: False
>  * /crazyflie_server/enable_parameters: True
>  * /crazyflie_server/firmwareParams/ctrlMel/i_range_m_z: 1500
>  * /crazyflie_server/firmwareParams/ctrlMel/i_range_xy: 2.0
>  * /crazyflie_server/firmwareParams/ctrlMel/i_range_z: 0.4
>  * /crazyflie_server/firmwareParams/ctrlMel/kR_xy: 70000
>  * /crazyflie_server/firmwareParams/ctrlMel/kR_z: 60000
>  * /crazyflie_server/firmwareParams/ctrlMel/kd_omega_rp: 200
>  * /crazyflie_server/firmwareParams/ctrlMel/kd_xy: 0.2
>  * /crazyflie_server/firmwareParams/ctrlMel/kd_z: 0.4
>  * /crazyflie_server/firmwareParams/ctrlMel/ki_m_z: 500
>  * /crazyflie_server/firmwareParams/ctrlMel/ki_xy: 0.05
>  * /crazyflie_server/firmwareParams/ctrlMel/ki_z: 0.05
>  * /crazyflie_server/firmwareParams/ctrlMel/kp_xy: 0.4
>  * /crazyflie_server/firmwareParams/ctrlMel/kp_z: 1.25
>  * /crazyflie_server/firmwareParams/ctrlMel/kw_xy: 20000
>  * /crazyflie_server/firmwareParams/ctrlMel/kw_z: 12000
>  * /crazyflie_server/firmwareParams/ctrlMel/mass: 0.032
>  * /crazyflie_server/firmwareParams/ctrlMel/massThrust: 132000
>  * /crazyflie_server/firmwareParams/flightmode/posCtrl: 1
>  * /crazyflie_server/firmwareParams/ring/effect: 14
>  * /crazyflie_server/firmwareParams/ring/headlightEnable: 0
>  * /crazyflie_server/firmwareParams/ring/solidBlue: 20
>  * /crazyflie_server/firmwareParams/ring/solidGreen: 0
>  * /crazyflie_server/firmwareParams/ring/solidRed: 0
>  * /crazyflie_server/force_no_cache: False
>  * /crazyflie_server/genericLogTopicFrequencies: [10]
>  * /crazyflie_server/genericLogTopic_log1_Variables: ['stabilizer.yaw'...
>  * /crazyflie_server/genericLogTopics: ['log1']
>  * /crazyflie_server/interactive_object: active-wand
>  * /crazyflie_server/markerConfigurations/0/numPoints: 4
>  * /crazyflie_server/markerConfigurations/0/offset: [0.0, -0.01, -0.04]
>  * /crazyflie_server/markerConfigurations/0/points/0: [-88.888206, 0.34...
>  * /crazyflie_server/markerConfigurations/0/points/1: [49.628719, -0.55...
>  * /crazyflie_server/markerConfigurations/0/points/2: [-89.778, 0.36277...
>  * /crazyflie_server/markerConfigurations/0/points/3: [-50.518517, -0.1...
>  * /crazyflie_server/motion_capture_type: optitrack
>  * /crazyflie_server/numDynamicsConfigurations: 1
>  * /crazyflie_server/numMarkerConfigurations: 1
>  * /crazyflie_server/object_tracking_type: libobjecttracker
>  * /crazyflie_server/optitrack_local_ip: 10.0.0.15
>  * /crazyflie_server/optitrack_server_ip: 10.0.0.2
>  * /crazyflie_server/print_latency: False
>  * /crazyflie_server/save_point_clouds: ~/pointCloud.ot
>  * /crazyflie_server/world_frame: /world
>  * /crazyflie_server/write_csvs: False
>  * /crazyflies: [{'initialPositio...
>  * /rosdistro: kinetic
>  * /rosversion: 1.12.7
> 
> NODES
>   /
>     crazyflie_manager (crazyflie_manager/crazyflie_manager)
>     crazyflie_server (crazyflie_driver/crazyflie_server)
>     rqt (rqt_gui/rqt_gui)
>     rviz (rviz/rviz)
> 
> auto-starting new master
> process[master]: started with pid [26268]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 1c70abce-6c8f-11e7-aa0a-e84e0638f12f
> process[rosout-1]: started with pid [26281]
> started core service [/rosout]
> process[crazyflie_server-2]: started with pid [26298]
> process[crazyflie_manager-3]: started with pid [26299]
> process[rviz-4]: started with pid [26306]
> [ INFO] [1500474757.584218376]: Wait for services...
> [ INFO] [1500474757.584597699]: waitForService: Service [/emergency] has not been advertised, waiting...
> process[rqt-5]: started with pid [26317]
> [ INFO] [1500474757.626254701]: waitForService: Service [/emergency] is now available.
> [ INFO] [1500474757.630550778]: Manager ready.
> NatNetClient connecting: 10.0.0.15 to 10.0.0.2...
> WARNING: Could not set receive buffer size. Asked for 1048576B got 0B
> [Client] Server Software: Motive
> [Client] NatNetVersion: 2.9
> [Client] ServerVersion: 1.90
> NatNet server version: 33554442
> ch: 1
> [ INFO] [1500474757.681092958]: Adding CF: cf1 (radio://0/100/2M/E7E7E7E701, cf1)...
> [ INFO] [1500474757.684933967]: CF ctor: 0.003688 s
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  timeout
> [crazyflie_server-2] process has died [pid 26298, exit code -6, cmd /home/xiaohao/bitcraze/crazyswarm/ros_ws/devel/lib/crazyflie_driver/crazyflie_server __name:=crazyflie_server __log:=/home/xiaohao/.ros/log/1c70abce-6c8f-11e7-aa0a-e84e0638f12f/crazyflie_server-2.log].
> log file: /home/xiaohao/.ros/log/1c70abce-6c8f-11e7-aa0a-e84e0638f12f/crazyflie_server-2*.log

I can connect my crazyflie through crazyflie-client. The related part of hover_swarm.launch as below,
```
<node pkg="crazyflie_driver" type="crazyflie_server" name="crazyflie_server" output="screen">
    <rosparam>
      #broadcast_address: "E7E7E7E701"
      broadcast_uri: "radio://0/100/2M/E7E7E7E701"
      world_frame: "/world"
      genericLogTopics: ["log1"]
      genericLogTopicFrequencies: [10]
```
crazyflies.yaml as below,
```
crazyflies:
- channel: 100
  id: 1
  initialPosition: [-842.6, -348.3, 58.2]

```
Do you know where goes wrong?

Thanks

**Comment by whoenig** [comment]
Please don't double post. I answered in the other thread (issue #13).
