### ISSUE TITLE
unable to test script in simulation

### ISSUE THREAD

**Issue by headhunter69** [USC-ACTLab/crazyswarm#227]
![Screenshot from 2020-06-26 14-24-56](https://user-images.githubusercontent.com/66996134/85840045-794acf00-b7b9-11ea-8cbc-c0febbec7597.png)
 i got this error.

**Comment by jpreiss** [comment]
for this script, your `crazyflies.yaml` must include exactly 6 crazyflies with the IDs corresponding to the array `ids` in the script. This error is caused by either 1) having more crazyflies in `crazyflies.yaml` beyond the 6 listed, or 2) not having the same IDs.
