### ISSUE TITLE
Possible dead code for polynomial trajectories

### ISSUE THREAD

**Issue by jpreiss** [USC-ACTLab/crazyswarm#231]
I think some of our polynomial trajectory code is redundant. `uav_trajectory.py` is active, but we also have

- `pycrazyswarm/piecewise.py` - basically a tool for loading CSV files into the firmware `struct piecewise_traj`. Is only used in `/old/` scripts, or commented out in other scripts. If we need this functionality again for some reason, we have a conversion from `uav_trajectory.Trajectory` to `firm.piecewise_traj` already implemented in `crazyflieSim.Crazyflie.uploadTrajectory()`.

- `pycrazyswarm/snap.py` is a minimum-snap trajectory optimization code copied from some other open source project. Is not used anywhere, except...

- ...`pycrazyswarm/trajectory.py` seems to be mostly a wrapper for going from the output format of `snap.py` directly to a `crazyflie_driver.msg.QuadcopterTrajectoryPoly` ROS message. It is only used in `/old/` scripts.

I think we could get rid of all of these... @whoenig is there any active use case I'm missing?

On a related note, most of the scripts in `/old/` look like they won't work because they use firmware features like ellipse and canned trajectories that we never contributed back to the Bitcraze firmware.

**Comment by whoenig** [comment]
I think we should delete those files. I usually recommend using https://github.com/whoenig/uav_trajectories for simple planning (and smoothener for more advanced planning). I don't think planning modules should be part of the Crazyswarm repo.

Also, I am fine with just deleting those scripts in `/old/`.
