### ISSUE TITLE
[crazyswarm_server-2] process has died

### ISSUE THREAD

**Issue by 864419409** [USC-ACTLab/crazyswarm#243]
When I run the following command
`zzw@zzw-ubuntu:~/crazyswarm0525/crazyswarm $ roslaunch crazyswarm hover_swarm.launch`
The following error occurred。Could you tell me how to deal with this？

> [crazyswarm_server-2] process has died [pid 9633, exit code -6, cmd /home/zzw/crazyswarm0525/crazyswarm/ros_ws/devel/lib/crazyswarm/crazyswarm_server __name:=crazyswarm_server __log:=/home/zzw/.ros/log/48a3edc4-e81e-11ea-92d8-200db010542d/crazyswarm_server-2.log].
> log file: /home/zzw/.ros/log/48a3edc4-e81e-11ea-92d8-200db010542d/crazyswarm_server-2*.log

When I did not join Ethernet, the following results appeared
```

```
> [ERROR] [1598503305.346880211]: Couldn't open joystick /dev/input/js0. Will retry every second.
> [ INFO] [1598503305.349818784]: Wait for services...
> [ INFO] [1598503305.350406457]: waitForService: Service [/emergency] could not connect to host [zzw-ubuntu:46297], waiting...
> [ INFO] [1598503305.371119577]: waitForService: Service [/emergency] is now available.
> [ INFO] [1598503305.372539044]: Manager ready.
> [ WARN] [1598503305.417398628]: Shutdown request received.
> [ WARN] [1598503305.417429417]: Reason given for shutdown: [new node registered with same name]
> [ WARN] [1598503305.419505602]: Shutdown request received.
> 
```
I've been able to successfully run a single drone in this version, but when I tried to use two drones to execute the above situation, and no more successful countries。

**Comment by whoenig** [comment]
This usually means that there was a segmentation fault, most frequently caused by a misconfiguration. Perhaps https://github.com/USC-ACTLab/crazyswarm/issues/147 will help?

**Comment by 864419409** [comment]
感谢您，问题已经解决了
