### ISSUE TITLE
Use python 3.6 in virtual environment

### ISSUE THREAD

**Issue by MauroPfister** [USC-ACTLab/crazyswarm#246]
Hi

I'm trying to use crazyswarm on Ubuntu 18.04 with python 3.6.9. In order not to pollute my system python I'm using `virtualenv` and `virtualenvwrapper` to create a virtual environment. So instead of installing the required python packages system-wide with 
```
$ sudo apt install git swig libpython-dev python-numpy python-yaml python-matplotlib gcc-arm-embedded libpcl-dev libusb-1.0-0-dev sdcc ros-kinetic-vrpn-client-ros
$ git clone https://github.com/USC-ACTLab/crazyswarm.git
$ cd crazyswarm
```
I activate my python 3.6 virtualenv and then do
```
$ sudo apt install git swig libpython-dev gcc-arm-embedded libpcl-dev libusb-1.0-0-dev sdcc ros-kinetic-vrpn-client-ros
$ pip install numpy pyyaml matplotlib
$ git clone https://github.com/USC-ACTLab/crazyswarm.git
$ cd crazyswarm
```

Unfortunately this does not seem to be enough. When I try to launch 
```
cd ros_ws/src/crazyswarm/scripts
python figure8_csv.py --sim
```
I get the following error:
```
Traceback (most recent call last):
  File "figure8_csv.py", line 9, in <module>
    swarm = Crazyswarm()
  File "/home/blabla/Develop/crazyswarm/ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyswarm.py", line 39, in __init__
    import crazyflieSim
ModuleNotFoundError: No module named 'crazyflieSim'
```

I saw that `python2` is used in the makefile of `cfsim`:
https://github.com/USC-ACTLab/crazyswarm/blob/dfd69b44fcb8fe78f11fa3d76e1a35e4cea715c8/ros_ws/src/crazyswarm/scripts/pycrazyswarm/cfsim/Makefile#L5-L6
I tried changing this to `python` (which aliases to python 3.6 in my virtualenv) and then rebuilding everything but that did not help. 

I'm a bit lost here and don't really know where to start searching. Any help is appreciated. 

Cheers

**Comment by whoenig** [comment]
Crazyswarm only supports Python2 at the moment. There is some ongoing effort (see #214) to support Python3, but as long as that is not resolved, we cannot offer support for Python3 here.
