### ISSUE TITLE
Effective range of 2M

### ISSUE THREAD

**Issue by 864419409** [USC-ACTLab/crazyswarm#250]
Hello, I want to ask what is the effective range of 2M, because I find that the effective range of PA is relatively small when 2M is chosen

**Comment by whoenig** [comment]
Bitcraze tested the range to be up to 1km outdoors. Indoors, this mostly depends on other devices in the 2.4 GHz band (Wifi, BlueTooth). Try different channels and use `rosrun crazyflie_tools comCheck` to gather some quantitative information for each channel choice.

**Comment by 864419409** [comment]
thank you very much.
