### ISSUE TITLE
CMakeList.txt tracked in Git

### ISSUE THREAD

**Issue by MauroPfister** [USC-ACTLab/crazyswarm#267]
Hi

I noticed that the autogenerated `CMakeList.txt` in `ros_ws/src` is included in the `crazyswarm` repo. This creates an issue when using a ROS version other than Kinetic and working on different branches, since the changed symbolic link results in a dirty working tree. I am not sure about best practices for ROS, but to me it seems like this file should not be tracked in Git.

Thanks for the support!

**Comment by whoenig** [comment]
Good point. This should be added to `.gitignore` and not part of the repo. I think having a workspace in git is fairly uncommon, so I am not sure if there are any best practices for our particular use-case.

**Comment by MauroPfister** [comment]
Hi @whoenig, are there any updates on this? Would it be possible to simply update `.gitignore` for the moment?

**Comment by acxz** [comment]
I think you would also need to run `git rm ros_ws/src/CMakeList.txt` to ensure it gets removed from the repo.
