### ISSUE TITLE
advice on markers layout and possible vicon settings

### ISSUE THREAD

**Issue by Hurisa** [USC-ACTLab/crazyswarm#270]
Hi everyone,

Is there any advice on the 4 markers layout (6.5mm) for the cf? I know it must be asymmetrical, but the fact is I can't get a stable point cloud. I'm using the mocap deck and attach a marker on one of the motor mounts similar to https://crazyswarm.readthedocs.io/en/latest/usage.html.
I have tried with a single larger marker (9.5mm) and then I could get stable tracking but the issue is that I want to send angular velocity commands to have the swarm flying autonomously and part of my algorithm is that each drone avoids its neighbours based on Pose.
Alternative is there particular properties for the vicon cameras that may help me?
I know this might be a bit vague but hopefully we can discuss some solution.

Thanks

**Comment by whoenig** [comment]
* In the camera view, make sure that you markers are visible (at least 3-5 pixels per marker in as many cameras as possible).
* In the 3D perspective view, you can select individual markers and lines are drawn that show you which camera can see that marker. Make sure that at least 4 cameras can see each marker in the desired flight volume. Adjusting camera position or angles can help to improve the coverage for your use case.
* For the 'unstable point cloud' check the raw camera view. You can also try reducing the IR strobe intensity, in case there are unwanted reflections. When you calibrate, make sure you are using the masking feature to avoid any spurious background detection.

**Comment by jpreiss** [comment]
Check the frame rate of your mocap system. Someone set our Vicon to 400Hz and it was causing all kinds of problems. Even 10 or 20 Hz should work fine.

If you have few CFs and marker decks, you could make a unique layout for each CF and use your mocap built in object tracking. It is generally more robust.

**Comment by Hurisa** [comment]
Thank you @jpreiss and @whoenig  so much for your advice.
I'll let you know if I make it! Fortunately I have access to my lab over the weekend.
