### ISSUE TITLE
There is no noetic version for vrpn

### ISSUE THREAD

**Issue by xyyjcyd** [USC-ACTLab/crazyswarm#280]
Now I am trying to run crazyswarm based on ubuntu20.0.4 & python3.8 & ros-noetic. When I tried to install the vrpn for distro ros-noetic, according to ROS index, I found there is still no version for Noetic. 
[https://index.ros.org/r/vrpn/#noetic](url)
![Screenshot_2020-12-07 ROS Index](https://user-images.githubusercontent.com/46839369/101348488-ab16a480-38c6-11eb-8a69-38306fd9b66a.png)

**Comment by jpreiss** [comment]
See discussion in https://github.com/USC-ACTLab/crazyswarm/issues/248. It appears that the ROS vrpn package doesn't support Noetic yet.

Crazyswarm interacts with the mocap system via https://github/com/USC-ACTLab/libmotioncapture. I believe libmotioncapture only needs the VRPN library, not the ROS package. In the past we used the ROS package as a  convenient way to get the VRPN library installed. You should be able to use VRPN by installing https://github.com/vrpn/vrpn such that CMake can find it. @whoenig is this correct?

**Comment by whoenig** [comment]
That's accurate - thanks!

**Comment by xyyjcyd** [comment]
> See discussion in #248. It appears that the ROS vrpn package doesn't support Noetic yet.
> 
> Crazyswarm interacts with the mocap system via https://github/com/USC-ACTLab/libmotioncapture. I believe libmotioncapture only needs the VRPN library, not the ROS package. In the past we used the ROS package as a convenient way to get the VRPN library installed. You should be able to use VRPN by installing https://github.com/vrpn/vrpn such that CMake can find it. @whoenig is this correct?

Thanks for your help!!

**Comment by lkyfly0765** [comment]
Actually, the natnet is more stable and easy to configure. See this [https://github.com/whoenig/NatNetSDKCrossplatform](https://github.com/whoenig/NatNetSDKCrossplatform)

**Comment by jpreiss** [comment]
@xyyjcyd were you able to get everything installed OK? If so, please close this issue.
