### ISSUE TITLE
CrazyFlie Bolt compatability

### ISSUE THREAD

**Issue by annesteenbeek** [USC-ACTLab/crazyswarm#285]
Hello,

I'm starting research on a new project, combining drone swarms and dance.
There are already UAV frames available, though some problems with the controllers.
I was hoping to replace the FCU with the [CrazyFlie Bolt](https://www.bitcraze.io/products/crazyflie-bolt/).
However, I can't find any information in the documentation on the compatibility of crazyswarm with this board.
I know the Bolt is still in early access, but is this something that would be supported or would it require additional work from my side to flash the swarm firmware on this board?

**Comment by whoenig** [comment]
It is supported, no custom firmware needed. Let us know if you run into any issues!

**Comment by annesteenbeek** [comment]
Great, good to know.
Thanks for the fast response.
