### ISSUE TITLE
PWM output saturation

### ISSUE THREAD

**Issue by swarm5** [USC-ACTLab/crazyswarm#290]
I encountered a problem. I installed 4 mark points and an SD card slot on my cf. During the takeoff of cf, cf's PWM output was saturated for a short time. During horizontal flight, this phenomenon does not exist. I would like to ask, how can I adjust it?

**Comment by swarm5** [comment]
I have an SD card slot, I can record all the parameters of the aircraft. If necessary, I can do experiments and plot graphs quickly.

**Comment by whoenig** [comment]
You could provide a longer takeoff time in your script, which should lower the thrust requirements. Otherwise you can also upgrade your battery or motors to avoid this problem.

**Comment by swarm5** [comment]
Thank you for your suggestion
