### ISSUE TITLE
How can I adjust the parameters when cf is overweight?

### ISSUE THREAD

**Issue by ucaszzw** [USC-ACTLab/crazyswarm#292]
Now my cf is about 37g, how can I adjust the parameters.
I use rigid body or single point tracking mode.
1. How should mass and massThrust be adjusted?
2. Does ctrlMel need to be changed accordingly?
3. Does the Kalman parameter need to be adjusted?

**Comment by jpreiss** [comment]
1. See https://github.com/USC-ACTLab/crazyswarm/issues/150#issuecomment-749010535 and following comments.
2. It shouldn't make a big difference, but if you observe instability you can try decreasing the gains a little.
3. No.
