### ISSUE TITLE
What parameters do I need to modify to replace a motor with a higher KV value?

### ISSUE THREAD

**Issue by swarm5** [USC-ACTLab/crazyswarm#296]
@jpreiss @whoenig Hello, I am currently experiencing a problem:
My cf is about 35g, and it is often unstable because of the saturation of the PWM output. Now I want to replace cf with a better performance motor. The KV value of the new motor is 18000, while the KV value of the official motor is 14000.
I would like to ask, if I change to a new motor, do I need to modify the parameters in` crazyflieTypes.yaml`? E.g:	        
1. `Mass: 0.032 `is modified to` mass: 0.035`
2. May I ask How much is `massThrust:  132000` modified?
3. Are there other parameters that need to be modified?

**Comment by whoenig** [comment]
Unfortunately, this requires to re-tune the controller, so many parameters need to be adjusted (depending on which controller you use). Tuning itself is typically a multi-stage process: 1) remove any i-gains; 2) reduce position controller gains and focus on attitude controller first with just hover flight; 3) tune position gains (e.g., figure-8 flight); this will also require minor adjustments of the parameters found in step 2); 4) re-add I gains (this in turn might require small adjustments of other parameters).

It is certainly doable, but can easily take 1-3 days to reach a satisfactory result. I find it helpful to log the stateEstimate as well as desired state to uSD card, and visualize the flight performance that way. You can also log over the radio, but you are typically much more limited in the number of variables you can look at at the same time.
