### ISSUE TITLE
Crazyflie Chooser Timeout / CalledProcessError

### ISSUE THREAD

**Issue by elim17** [USC-ACTLab/crazyswarm#297]
Hello, 

When I run the crazyflie chooser.py all of the options(sysOff, reboot, flash) all report a timeout. The battery option gives a CalledProcessError. I can run `rosrun crazyflie_tools scan -v --address xxxxxxxxx` and that works. When I run `rosrun  crazyflie_tools battery` it gives a timeout. Does anyone know how to fix this?

**Comment by elim17** [comment]
Update: It turns out that the radio channel didn't match. Once I made sure the Chanel matched in allcrazyflies.yaml it worked.

**Comment by whoenig** [comment]
Great - thanks for the update. Closing.
