### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by elim17** [USC-ACTLab/crazyswarm#331]
Based on what was said on this page [https://github.com/USC-ACTLab/crazyswarm/issues/32](url) I should not have to run a vrpn client node to connect to motive Optitrack. When I do not, however, nothing shows up in Rviz. We are running Optitrack on its own workstation that has windows. On a separate workstation that runs linux, we are running the crazy swarm software. Any ideas on what is causing the disconnect when not using vrpn? Thank you!

**Comment by whoenig** [comment]
For Optitrack related issues, please verify that NatNet works for you, using the following repository: https://github.com/whoenig/NatNetSDKCrossplatform. The Crazyswarm internally simply uses that SDK for communication with OptiTrack.
