### ISSUE TITLE
No Updated Pose for Motion Capture Object

### ISSUE THREAD

**Issue by elim17** [USC-ACTLab/crazyswarm#348]
Hello,

Our `mocap_helper.launch` is working and streaming motion-capture data via NatNet.  We can see the correct changes in pose. However, when running hover_swarm.launch we receive these warnings: 
![Screenshot from 2021-03-19 13-49-35](https://user-images.githubusercontent.com/42954721/111916605-58aa5f80-8a41-11eb-9fe9-44dc36591cbb.png)

The "No Updated Pose for Motion Capture Object" warning is most troublesome to us because the drones will take off but flight is unpredictable and ends with them running into a wall. Any suggestions on where this warning is coming from? It looks like motion capture was not implemented in previous issues where this error was received(2018-2019 issues). From other conversations it looks like motion capture was implemented since then with motive Optitrack.

**Comment by whoenig** [comment]
Could you provide a screenshot/printout of `mocap_helper.launch`? My initial guess is that there is a mismatch in the naming of the rigid body in motive (needs to be `cf2` for `hover_swarm.launch` to work, while `mocap_helper.launch` simply prints all data it receives).

**Comment by elim17** [comment]
Unfortunately, It seems like my naming convention is correct. This is the output for `mocap_helper.launch`. 
![Screenshot from 2021-03-23 11-09-00](https://user-images.githubusercontent.com/42954721/112205604-95f62500-8bda-11eb-939b-a19ec28cfba7.png)

I did make the cf rigid bodies in Motive, in order as it says to do on your GitHub. This is the test output with both cf1 and cf2 selected. 
![Screenshot from 2021-03-23 11-20-46](https://user-images.githubusercontent.com/42954721/112205771-c938b400-8bda-11eb-86e9-4bf726273013.png)

Then I tried `hover_swarm.launch` with both cf1 and cf2. I get an output warning for both. 
![Screenshot from 2021-03-23 11-21-03](https://user-images.githubusercontent.com/42954721/112205884-ea99a000-8bda-11eb-8e6f-0af07fa82343.png)

What would be your next guess?

**Comment by whoenig** [comment]
Is your tracking type set to motionCapture (https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L36)? If yes, please share both your mocap_helper and your hover_swarm launch files.

**Comment by elim17** [comment]
Yes, our tracking type is set to motionCapture.

Below are the mocap_helper and hover_swarm launch files. 
![Screenshot from 2021-03-24 14-06-54](https://user-images.githubusercontent.com/42954721/112377437-5b0ff200-8cab-11eb-904f-953903679258.png)

![Screenshot from 2021-03-24 14-08-57](https://user-images.githubusercontent.com/42954721/112377447-5f3c0f80-8cab-11eb-8355-d6ac0dbcfeb8.png)

**Comment by whoenig** [comment]
This is very odd, but also probably a code path that wasn't tested in a long while (since using rigid bodies is not that useful for larger teams). One thing that would be helpful is too add `ROS_INFO("rb %s", rigidBody.name());` in https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/src/crazyswarm_server.cpp#L1123. I reviewed the code and didn't see any obvious mistake, but this would at least tell us if the rigid bodies are correctly identified in at least some of the frames. Don't forget to use `catkin_make` after changing the code.

**Comment by elim17** [comment]
You were right! The rigid bodies don't seem to be correctly identified as were are receiving what looks like empty string. 
![Screenshot from 2021-03-25 12-35-34](https://user-images.githubusercontent.com/42954721/112531199-ea310e80-8d6c-11eb-9a1d-3b5eab2f4040.png)
![Screenshot from 2021-03-25 12-38-29](https://user-images.githubusercontent.com/42954721/112531205-eb623b80-8d6c-11eb-9de5-bdc62370cb9f.png)

**Comment by jpreiss** [comment]
The `?????` output is probably a null pointer, not an empty string.

**Comment by elim17** [comment]
Ok, is that what you were expecting to get from the previous post? It seems like either way the rigid body is not being identified.

**Comment by elim17** [comment]
@whoenig Do you have any suggestions based on the null pointer issue?

**Comment by whoenig** [comment]
Not sure. You could try adding some more debugging prints here https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/src/crazyswarm_server.cpp#L1707, to see if directly after the call to libmotioncapture the data itself is valid or not. It looks like some sort of memory corruption, but I am not sure on which level it occurs. Another option is to run the crazyswarm server with valgrind (http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB).

**Comment by elim17** [comment]
After debugging it was found that the calibration of our motion capture system was to blame. When using rigid body streaming, the number of markers and steadiness of the rigid body is paramount. When a marker doesn't show or the rigid body is unstable crazy swarm throws a 'No Updated Pose for motion capture object...'. After recalibration we are no longer getting those warnings.

**Comment by whoenig** [comment]
Thanks for letting us know!

**Comment by hit-JB** [comment]
@elim17 
Hello have you sole the "No updated pose" problem ,i encountered the same problem as you .Could you give me some advice how you did it? The Info is as blow
`
[ WARN] [1639884992.966357304]: No updated pose for CF cf1 for 1639884992.966298 s.
[ WARN] [1639884992.976571012]: No updated pose for CF cf1 for 1639884992.976451 s.
[ WARN] [1639884992.986326886]: No updated pose for CF cf1 for 1639884992.986274 s.
[ WARN] [1639884992.996349832]: No updated pose for CF cf1 for 1639884992.996289 s.
[ WARN] [1639884993.006453691]: No updated pose for CF cf1 for 1639884993.006391 s.
[ WARN] [1639884993.016369565]: No updated pose for CF cf1 for 1639884993.016309 s.
[ WARN] [1639884993.026424988]: No updated pose for CF cf1 for 1639884993.026348 s.
[ WARN] [1639884993.036433558]: No updated pose for CF cf1 for 1639884993.036373 s.
[ WARN] [1639884993.046464267]: No updated pose for CF cf1 for 1639884993.046405
`

**Comment by whoenig** [comment]
@hit-JB: This is a closed issue and you won't get an answer here. Try the github discussions instead.
