### ISSUE TITLE
cmdVel not implemented for simulation

### ISSUE THREAD

**Issue by Cafolkes** [USC-ACTLab/crazyswarm#369]
Hi,

we are planning to use the cmdVel command to send attitude + thrust commands (roll, pitch, yawrate, thrust) to the crazyflies using the Python API. However, cmdVel is not implemented in the crazyflieSim class, so when running our code in simulation the crazyflie object does not have a cmdVel method. Is there a way of replicating the cmdVel functionality with methods already implemented in the crazyflieSim class or can you please give some hints on the easiest way to implement cmdVel with the simulator?

Thank you for your great work!

**Comment by jpreiss** [comment]
You can look at the `cmdVelocityWorld` and `integrate` methods in `crazyflieSim.py` to get an idea of what needs to be done. It would require adding a second-order integration step using the acceleration vector derived from the (r, p, y, thrust) command.

**Comment by jpreiss** [comment]
@Cafolkes did you work on this at all? If so, please consider contributing a PR. I think other users would benefit from this feature.

**Comment by jpreiss** [comment]
closed due to inactivity.
