### ISSUE TITLE
Cannot flash radio

### ISSUE THREAD

**Issue by aldrinchua8** [USC-ACTLab/crazyswarm#40]
Hi, 
I an getting an error when I try to flash the radio using the "option 2" method. The error is shown below
![image](https://user-images.githubusercontent.com/32363552/34914895-d0d2ce18-f956-11e7-9937-d6381f91fe39.png)
I do have the crazyradio upgraded to 99.55 but I am not sure if I am using the crazyradio PA or not. because in the "README" file, it seems that the you can choose if it is crazyradio PA or not. how can i check if I have the crazyradio PA?

**Comment by whoenig** [comment]
1. You need to run the command as sudo or add a udev-file (see "Flying Multiple UAVs Using ROS", Chapter in Robot Operating System (ROS): The Complete Reference (Volume 2), Springer, 2017. ; pre-print at http://act.usc.edu/publications.html).

2. There should be some text on your radio indicating "Crazyradio" or "Crazyradio PA".

**Comment by aldrinchua8** [comment]
Thanks! adding sudo made it work!
