### ISSUE TITLE
Marker Configuration

### ISSUE THREAD

**Issue by javieryu** [USC-ACTLab/crazyswarm#46]
What is the best way to define the marker layout for the launch file? I am using a VICON system right, now and I can't figure out a good way to get accurate offset and marker positions for the layout.

**Comment by whoenig** [comment]
1. Place the CF at the center facing forward.
2. Use the 3D positions of the markers as the points in your configuration. There is a helper script for that in a [different branch](https://github.com/USC-ACTLab/crazyswarm/blob/bigQuad/ros_ws/src/crazyswarm/launch/mocap_helper.launch)
3. As offset just use the z-portion to adjust for the center of mass. We use rviz to visualize the estimated pose and the marker point cloud to do so.
