### ISSUE TITLE
Python APIs are not shown in the document

### ISSUE THREAD

**Issue by loujiabin1994** [USC-ACTLab/crazyswarm#463]
Hello, these days I want to look up the python API of crazyflie class, but it's not shown in docs.
[https://crazyswarm.readthedocs.io/en/latest/api.html#crazyflie-class](url)

**Comment by The-SS** [comment]
I noticed this as well. 
While it may be less convenient, the comments/docstrings in [crazyflie.py](https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyflie.py) are basically what you are looking for.

**Comment by jpreiss** [comment]
Should be an easy fix.

It's annoying that our docs build in CI shows the message

    WARNING: autodoc: failed to import class 'crazyflie.CrazyflieServer' from module 'pycrazyswarm';
    the following exception was raised:
    No module named 'numpy'

but doesn't return a nonzero exit code. Maybe we can configure autodoc differently or parse the output.

**Comment by jpreiss** [comment]
Fixed by #480 and 73cce6b. Changed warnings to errors in docs CI.
