### ISSUE TITLE
Docs for single-marker tracking

### ISSUE THREAD

**Issue by jpreiss** [USC-ACTLab/crazyswarm#484]
We briefly mention single-marker tracking in the front page and changelog, but provide no details. Ideally we would discuss:

- Trade-offs with multi-marker `libobjecttracker`
- Step-by-step guide for the configuration file changes
- Guidelines for flight (e.g. how long can we hover)

**Comment by whoenig** [comment]
Great idea, this is on my plate! I was planning to do that for a while.
