### ISSUE TITLE
Error running pytest test after installation

### ISSUE THREAD

**Issue by Sherry-97** [USC-ACTLab/crazyswarm#528]
After I finished installing crazyswarm on **ubuntu 18.04**, I ran **pytest**  for testing and encountered an error that I had not encountered before in ubuntu16.04. I don't know if this error has any effect on the later work, details are as follows.

![Selection_001](https://user-images.githubusercontent.com/70084772/140855558-54192778-1cfa-49e2-b0a0-893e4bf90849.png)

Thank you very much!

**Comment by jpreiss** [comment]
don't worry about it - it's an optional feature.
