### ISSUE TITLE
How to calcurate Thrust from  cmdFullState command   

### ISSUE THREAD

**Issue by KT1024-kei** [USC-ACTLab/crazyswarm#558]
Hi, I'm Japanese college student. 
Now I use CmdFullState command for Trajectory Tracking. And want to know how CmdFullState calculate input Thrust.
Correct formula is thrust = -Kp*ep - Ke*ev + m*g*Zw + m*r_2dotT ?? from "Minimum  Snap  Trajectory  Generation  and  Control  for  Quadrotors".

Which file is used to calculate this formula ?? I found pptraj.c in crazyswarm/crazyflie-firmware/src/modules/src and I think this file calculate trajectories.
But I couldn't find file which use above formula. where is it ??

thanks.

**Comment by jpreiss** [comment]
This question pertains only to the Crazyflie firmware, not to the Crazyswarm project. Please ask it in [the Bitcraze developer forum](https://forum.bitcraze.io/viewforum.php?f=6&sid=93fc03c9f00a690b5192257eb9cf3071).
