### ISSUE TITLE
Crazyflie crashes after flying ~14m

### ISSUE THREAD

**Issue by pPatrickK** [USC-ACTLab/crazyswarm#56]
Hi Guys,

3 Observations which we think belong to the same issue:

1.
we try to fly the crazyflie for 8 meters (start @ 0,0,0) on y axis at 0.3m altitude. After ca ~6.5 meters the drone "jumps" higher and crashes into the ground. The drone is still tracked by the motion capture system.

If we let the drone start a 8 meters (start@ 0,8,0) on the y axis, it is good tracked and takes off, but if we want to fly to the origin (negative y direction) it flies in the opposite (positive y) direction up to the wall. 

2.
We try to fly the crazyflie for 15 meters (start@ -8,0,0) on x axis at 0.3m altitude. After ca 14 meters the drone "jumps" higher and crashes into the ground. The drone is still tracked by the motion capture system.

3.
If we let the drone start a 9 meters (start@ 9,0,0) on the y axis, it is good tracked and takes off, but if we want to fly to the origin (negative x direction) it flies in the opposite (positive x) direction up to the wall. 

What could be the problem and a possible solution?

We use the following script:
```
#!/usr/bin/env python

import numpy as np
from pycrazyswarm import *

Z = 0.3

if __name__ == "__main__":
    swarm = Crazyswarm()
    timeHelper = swarm.timeHelper
    allcfs = swarm.allcfs

    allcfs.takeoff(targetHeight=Z, duration=1.0+Z)
    timeHelper.sleep(1.5+Z)
    for cf in allcfs.crazyflies:
        pos = np.array(cf.initialPosition) + np.array([15, 0, Z])
        cf.hover(pos, 0, 25.0)

    print("press button to continue...")
    swarm.input.waitUntilButtonPressed()

    allcfs.land(targetHeight=0.02, duration=1.0+Z)
    timeHelper.sleep(1.0+Z)

```
The hall has a size of 30m x 15m x 10m. We use 38 cameras of the company Vicon for our setup. The dron is a Crazyflie 2. We use two computers, one for the motion capture and one for crazyswarm.

**Comment by jpreiss** [comment]
We haven't seen bugs like this, but we also haven't flown quite so far from the origin in our experiments. A couple of questions:

1. Can you reproduce this bug in simulation mode (by appending `--sim` to your python script)?

2. Does the issue persist if you use vicon's rigid body tracking instead of libobjecttracker? (change `object_tracking_type` to `motionCapture` and create an object in vicon tracker with the same name as your Crazyflie, e.g. cf1)

**Comment by whoenig** [comment]
I guess this is related to our [hardcoded position limit](https://github.com/USC-ACTLab/crazyflie-firmware/blob/crazyswarm-next/src/modules/interface/packetdef.h#L49) of +/- 8m. For your space change the value to at least 15, and recompile both firmware and the ros workspace. I believe this limit is not exposed in the simulator, so the simulation should still behave correctly.

**Comment by jpreiss** [comment]
We should simplify this code to use integer number of millimeters...

**Comment by whoenig** [comment]
That's already done [upstream](https://github.com/bitcraze/crazyflie-firmware/pull/310). This will, however, still limit the space to +/-16m, similar to your new fullPoseSetPoint.

**Comment by pPatrickK** [comment]
That worked.

Thank you very much for the quick response

Best regards
Patrick
