### ISSUE TITLE
Hi, I am currently starting to work with crazyswarm and crazyflies(2.1).

### ISSUE THREAD

**Issue by GideonLombardo** [USC-ACTLab/crazyswarm#606]
Hi, I am currently starting to work with crazyswarm and crazyflies(2.1).

I installed and configured everything, but I have big troubles with the first hovering with HW.

Everytime I execute the hello_world.py, the crazyflie flips over or flies somewhere. 
I already tried to balance everything and also tried to start the drone manually (which is working completely fine)

I also tried to change the drone, but the issue remains.

Is it possible, that I made a mistake, when setting up crazyswarm?

Thank you in advance!

Regards Florian

_Originally posted by @flrnhbr1 in https://github.com/USC-ACTLab/crazyswarm/discussions/603_

I have this same issue. My error message is as follows:

Warning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

cfg = yaml.load(crazyflies_yaml)

Warning: No joystick found!

Traceback (most recent call last):

File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 567, in connect

self.socket.connect((dest_addr, dest_port))

ConnectionRefusedError: [Errno 111] Connection refused

I believe it might be an issue with the radio communication. I cannot determine whether the issue is on the radio's end or the crazyflie's end.

**Comment by whoenig** [comment]
Please see the discussion in https://github.com/USC-ACTLab/crazyswarm/discussions/603. If your problem is unrelated, open a new discussion topic.

**Comment by GideonLombardo** [comment]
I will take a look. Thank you for all your help and patience as I try to get this up and running for my lab. I am learning as I go, so it really helps to have a support structure like the discussions on Github.
________________________________
From: Wolfgang Hönig ***@***.***>
Sent: Tuesday, March 8, 2022 11:59 AM
To: USC-ACTLab/crazyswarm ***@***.***>
Cc: Gideon Lombardo ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [USC-ACTLab/crazyswarm] Hi, I am currently starting to work with crazyswarm and crazyflies(2.1). (Issue #606)


Please see the discussion in #603<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSC-ACTLab%2Fcrazyswarm%2Fdiscussions%2F603&data=04%7C01%7Cgllombardo%40crimson.ua.edu%7Cab848cfd88c54058986008da012d71b4%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637823591945177134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yLnEt1zdOJtVQFYuxtK4Dp8sI%2BOztDfw%2Fcylp6FiTDw%3D&reserved=0>. If your problem is unrelated, open a new discussion topic.

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUSC-ACTLab%2Fcrazyswarm%2Fissues%2F606%23issuecomment-1062053296&data=04%7C01%7Cgllombardo%40crimson.ua.edu%7Cab848cfd88c54058986008da012d71b4%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637823591945177134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MO5R6yHDOB5HJrc0aFkt5ItZJ8a9lYrFXY5A%2B3lCYbU%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXZAOPBRXSBSEEAFKLB7DN3U66IRPANCNFSM5P4CEJ7A&data=04%7C01%7Cgllombardo%40crimson.ua.edu%7Cab848cfd88c54058986008da012d71b4%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637823591945177134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=r%2FOYbPg2WS7lY1DXWfLlDAz38yDEbCkhQIzmG7s0w04%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cgllombardo%40crimson.ua.edu%7Cab848cfd88c54058986008da012d71b4%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637823591945177134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KwbstEHw8s0qS9Kzk5qI2MCknS3WukVtJ6u7u77Wtj8%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cgllombardo%40crimson.ua.edu%7Cab848cfd88c54058986008da012d71b4%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637823591945177134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uC9xU%2FP3Jg1RqUVr98Zzdg1IObGUfgLo1nyW9dCMqv4%3D&reserved=0>.
