### ISSUE TITLE
NRF firmware update issue

### ISSUE THREAD

**Issue by srnetsr** [USC-ACTLab/crazyswarm#61]
Hi,
recently I bought new cf2.
To update firmwares following
[http://crazyswarm.readthedocs.io/en/latest/usage.html](http://crazyswarm.readthedocs.io/en/latest/usage.html),
I executed `rosrun crazyflie_tools flash --target nrf51 --filename cf2_nrf.bin`
But I got `timeout` error.
It did not work at all.
Do you have any idea to update firmwares?

`rosrun crazyflie_tools flash --target stm32 --filename prebuilt/cf2.bin` did not work neither...
Is my crazyradioPA problem?

P.S. when I run `rosrun crazyflie_tools scan`, it shows only `radio://0/80/2M`
but when I run `lsusb -d 1915:7777 -v | grep bcdDevice`, it shows `bcdDevice           99.55`

**Comment by whoenig** [comment]
There is currently unfortunately a bug preventing the flash tool to work properly in many cases. As workaround, you can use the official flashing tool, that is part of the bitcraze python lib:
```
python3 -m cfloader flash prebuilt/cf2.bin stm32-fw
python3 -m cfloader flash prebuilt/cf2_nrf.bin nrf51-fw
```

Note that the official tools unfortunately do not execute a verification step, so place the CF very close to the radio.

**Comment by srnetsr** [comment]
Thanks.
it works.
