### ISSUE TITLE
Server crashes at start

### ISSUE THREAD

**Issue by pPatrickK** [USC-ACTLab/crazyswarm#63]
Hello,
sometimes, the server crashes at start. We saw that it is while one drone isn't seen ore there is no connection to one drone.
If the drone isn't visible for the ICP, we have the same issue. We like to have a more robust behavior, so that the server is still running and can fly the other drones, while ignoring the drones not found. Is there a way to fix this problem? Maybe a hint for us to implement this behavior?

This is the error message (the log file does not exist):

> ... logging to /home/flw/.ros/log/4a549a4c-5842-11e8-869b-509a4c5316eb/roslaunch-flw-25522.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> WARNING: disk usage in log directory [/home/flw/.ros/log] is over 1GB.
> It's recommended that you use the 'rosclean' command.
> 
> started roslaunch server http://flw:36285/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /crazyflieTypes/default/batteryVoltageWarning: 3.8
>  * /crazyflieTypes/default/batteryVoltateCritical: 3.7
>  * /crazyflieTypes/default/bigQuad: False
>  * /crazyflieTypes/default/dynamicsConfiguration: 0
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/i_range_m_z: 1500
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/i_range_xy: 2.0
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/i_range_z: 0.4
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/kR_xy: 70000
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/kR_z: 60000
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/kd_omega_rp: 200
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/kd_xy: 0.2
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/kd_z: 0.4
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/ki_m_z: 500
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/ki_xy: 0.05
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/ki_z: 0.05
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/kp_xy: 0.4
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/kp_z: 1.25
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/kw_xy: 20000
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/kw_z: 12000
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/mass: 0.032
>  * /crazyflieTypes/default/firmwareParams/ctrlMel/massThrust: 132000
>  * /crazyflieTypes/default/markerConfiguration: 0
>  * /crazyflieTypes/large/batteryVoltageWarning: 11.4
>  * /crazyflieTypes/large/batteryVoltateCritical: 11.1
>  * /crazyflieTypes/large/bigQuad: True
>  * /crazyflieTypes/large/dynamicsConfiguration: 0
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/i_range_m_z: 1500
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/i_range_xy: 2.0
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/i_range_z: 4.0
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/kR_xy: 30000
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/kR_z: 40000
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/kd_omega_rp: 100
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/kd_xy: 3.0
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/kd_z: 3.0
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/ki_m_z: 500
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/ki_xy: 1.0
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/ki_z: 2.0
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/kp_xy: 8.0
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/kp_z: 8.0
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/kw_xy: 9000
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/kw_z: 10000
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/mass: 0.38
>  * /crazyflieTypes/large/firmwareParams/ctrlMel/massThrust: 5400
>  * /crazyflieTypes/large/markerConfiguration: 2
>  * /crazyflieTypes/medium/batteryVoltageWarning: 7.6
>  * /crazyflieTypes/medium/batteryVoltateCritical: 7.4
>  * /crazyflieTypes/medium/bigQuad: True
>  * /crazyflieTypes/medium/dynamicsConfiguration: 0
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/i_range_m_z: 1500
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/i_range_xy: 2.0
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/i_range_z: 2.0
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/kR_xy: 50000
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/kR_z: 60000
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/kd_omega_rp: 200
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/kd_xy: 1.0
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/kd_z: 1.0
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/ki_m_z: 500
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/ki_xy: 0.1
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/ki_z: 0.5
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/kp_xy: 2.0
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/kp_z: 3
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/kw_xy: 16000
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/kw_z: 12000
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/mass: 0.11
>  * /crazyflieTypes/medium/firmwareParams/ctrlMel/massThrust: 23000
>  * /crazyflieTypes/medium/markerConfiguration: 1
>  * /crazyflies: [{'initialPositio...
>  * /crazyswarm_server/broadcast_address: FFE7E7E7E7
>  * /crazyswarm_server/enable_logging: True
>  * /crazyswarm_server/enable_parameters: True
>  * /crazyswarm_server/firmwareParams/commander/enHighLevel: 1
>  * /crazyswarm_server/firmwareParams/kalmanUSC/rstWithExtPos: 1
>  * /crazyswarm_server/firmwareParams/ring/effect: 14
>  * /crazyswarm_server/firmwareParams/ring/headlightEnable: 0
>  * /crazyswarm_server/firmwareParams/ring/solidBlue: 255
>  * /crazyswarm_server/firmwareParams/ring/solidGreen: 0
>  * /crazyswarm_server/firmwareParams/ring/solidRed: 0
>  * /crazyswarm_server/force_no_cache: False
>  * /crazyswarm_server/genericLogTopicFrequencies: [10]
>  * /crazyswarm_server/genericLogTopic_log1_Variables: ['ctrlStat.edist']
>  * /crazyswarm_server/genericLogTopics: ['log1']
>  * /crazyswarm_server/motion_capture_type: vicon
>  * /crazyswarm_server/object_tracking_type: motionCapture
>  * /crazyswarm_server/print_latency: False
>  * /crazyswarm_server/save_point_clouds: ~/pointCloud.ot
>  * /crazyswarm_server/vicon_host_name: 192.168.2.182:801
>  * /crazyswarm_server/world_frame: /world
>  * /crazyswarm_server/write_csvs: False
>  * /crazyswarm_teleop/csv_file: /home/flw/Dokumen...
>  * /crazyswarm_teleop/timescale: 0.8
>  * /dynamicsConfigurations/0/maxFitnessScore: 0.001
>  * /dynamicsConfigurations/0/maxPitch: 1.4
>  * /dynamicsConfigurations/0/maxPitchRate: 20.0
>  * /dynamicsConfigurations/0/maxRoll: 1.4
>  * /dynamicsConfigurations/0/maxRollRate: 20.0
>  * /dynamicsConfigurations/0/maxXVelocity: 2.0
>  * /dynamicsConfigurations/0/maxYVelocity: 2.0
>  * /dynamicsConfigurations/0/maxYawRate: 10.0
>  * /dynamicsConfigurations/0/maxZVelocity: 3.0
>  * /joy/dev: /dev/input/js0
>  * /markerConfigurations/0/numPoints: 4
>  * /markerConfigurations/0/offset: [0.0, -0.01, -0.04]
>  * /markerConfigurations/0/points/0: [0.0177184, 0.013...
>  * /markerConfigurations/0/points/1: [-0.0262914, 0.05...
>  * /markerConfigurations/0/points/2: [-0.0328889, -0.0...
>  * /markerConfigurations/0/points/3: [0.0431307, -0.03...
>  * /markerConfigurations/1/numPoints: 4
>  * /markerConfigurations/1/offset: [0.0, 0.0, -0.03]
>  * /markerConfigurations/1/points/0: [-0.00896228, -0....
>  * /markerConfigurations/1/points/1: [-0.0156318, 0.09...
>  * /markerConfigurations/1/points/2: [0.0461693, -0.08...
>  * /markerConfigurations/1/points/3: [-0.0789959, -0.0...
>  * /markerConfigurations/2/numPoints: 4
>  * /markerConfigurations/2/offset: [0.0, 0.0, -0.06]
>  * /markerConfigurations/2/points/0: [0.0558163, -0.00...
>  * /markerConfigurations/2/points/1: [-0.0113941, 0.00...
>  * /markerConfigurations/2/points/2: [-0.0306277, 0.05...
>  * /markerConfigurations/2/points/3: [0.0535816, -0.04...
>  * /numDynamicsConfigurations: 1
>  * /numMarkerConfigurations: 3
>  * /rosdistro: kinetic
>  * /rosversion: 1.12.13
> 
> NODES
>   /
>     crazyswarm_server (crazyswarm/crazyswarm_server)
>     crazyswarm_teleop (crazyswarm/crazyswarm_teleop)
>     joy (joy/joy_node)
>     rviz (rviz/rviz)
> 
> auto-starting new master
> process[master]: started with pid [25532]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 4a549a4c-5842-11e8-869b-509a4c5316eb
> process[rosout-1]: started with pid [25545]
> started core service [/rosout]
> process[crazyswarm_server-2]: started with pid [25562]
> ERROR: cannot launch node of type [joy/joy_node]: joy
> ROS path [0]=/opt/ros/kinetic/share/ros
> ROS path [1]=/home/flw/Dokumente/crazyswarm/ros_ws/src
> ROS path [2]=/opt/ros/kinetic/share
> process[crazyswarm_teleop-4]: started with pid [25563]
> process[rviz-5]: started with pid [25564]
> [ INFO] [1526390237.780972131]: Wait for services...
> [ INFO] [1526390237.781326783]: waitForService: Service [/emergency] has not been advertised, waiting...
> [ INFO] [1526390237.802033939]: waitForService: Service [/emergency] is now available.
> [ INFO] [1526390237.803288839]: Manager ready.
> ch: 1
> [ INFO] [1526390237.855845087]: Adding CF: cf20 (radio://0/80/2M/E7E7E7E714, cf20)...
> [ INFO] [1526390237.858593916]: CF ctor: 0.002684 s
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  timeout
> [crazyswarm_server-2] process has died [pid 25562, exit code -6, cmd /home/flw/Dokumente/crazyswarm/ros_ws/devel/lib/crazyswarm/crazyswarm_server __name:=crazyswarm_server __log:=/home/flw/.ros/log/4a549a4c-5842-11e8-869b-509a4c5316eb/crazyswarm_server-2.log].
> log file: /home/flw/.ros/log/4a549a4c-5842-11e8-869b-509a4c5316eb/crazyswarm_server-2*.log
>

**Comment by whoenig** [comment]
The timeout happens if the drone can't connect. This might be connected to another issue, where the latest version of crazyflie_cpp had too low timeout values (I just merged a fix, see https://github.com/whoenig/crazyflie_cpp/commit/c402f4312f3b67e8c491ec2e6e210903e2f39934; you'll need to update your crazyflie_cpp manually).

If you want to keep going instead of ending crazyswarm_server, you can add an exception handler here: https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/src/crazyswarm_server.cpp#L1018.
