### ISSUE TITLE
Build and launch errors on new machines

### ISSUE THREAD

**Issue by pPatrickK** [USC-ACTLab/crazyswarm#65]
We tried to setup some more machines because we were curious if we only get our problems on our used machine. On one machine, we made a clean install of ubuntu 16.04 and started to install the dependencies and tried to build the repository. We get some strange error while building:

    CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
    Could not find a package configuration file provided by "crazyflie_cpp"
    with any of the following names:

    crazyflie_cppConfig.cmake
    crazyflie_cpp-config.cmake

    Add the installation prefix of "crazyflie_cpp" to CMAKE_PREFIX_PATH or set
    "crazyflie_cpp_DIR" to a directory containing one of the above files. If
    "crazyflie_cpp" provides a separate development package or SDK, be sure it
    has been installed.
    Call Stack (most recent call first):
    crazyswarm/CMakeLists.txt:7 (find_package)

    -- Could not find the required component 'crazyflie_cpp'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
    CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
    Could not find a package configuration file provided by "crazyflie_cpp"
    with any of the following names:

    crazyflie_cppConfig.cmake
    crazyflie_cpp-config.cmake

    Add the installation prefix of "crazyflie_cpp" to CMAKE_PREFIX_PATH or set
    "crazyflie_cpp_DIR" to a directory containing one of the above files. If
    "crazyflie_cpp" provides a separate development package or SDK, be sure it
    has been installed.
    Call Stack (most recent call first):
    crazyswarm/CMakeLists.txt:7 (find_package)

    -- Configuring incomplete, errors occurred!
    See also "/home/cardinal/Dokumente/crazyswarm/ros_ws/build/CMakeFiles/CMakeOutput.log".
    See also "/home/cardinal/Dokumente/crazyswarm/ros_ws/build/CMakeFiles/CMakeError.log".
    Invoking "cmake" failed
``

We used another machine where the build ran correctly but we couldn't launch the crazyflie server. It failed waiting for emergency service.

```
NODES
  /
    crazyswarm_server (crazyswarm/crazyswarm_server)
    crazyswarm_teleop (crazyswarm/crazyswarm_teleop)
    joy (joy/joy_node)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [79525]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to be87f40e-5aae-11e8-8373-e0d55e242924
process[rosout-1]: started with pid [79538]
started core service [/rosout]
process[crazyswarm_server-2]: started with pid [79555]
/home/porthos/Documents/crazyswarm/ros_ws/devel/lib/crazyswarm/crazyswarm_server: error while loading shared libraries: libboost_unit_test_framework-mt.so.1.55.0: cannot open shared object file: No such file or directory
ERROR: cannot launch node of type [joy/joy_node]: joy
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/porthos/Documents/crazyswarm/ros_ws/src
ROS path [2]=/opt/ros/kinetic/share
process[crazyswarm_teleop-4]: started with pid [79556]
[ INFO] [1526656720.774489077]: hallo-1
[ INFO] [1526656720.774678921]: hallo0
process[rviz-5]: started with pid [79557]
[ INFO] [1526656720.789263651]: Wait for services...
[ INFO] [1526656720.790776347]: waitForService: Service [/emergency] has not been advertised, waiting...
[crazyswarm_server-2] process has died [pid 79555, exit code 127, cmd /home/porthos/Documents/crazyswarm/ros_ws/devel/lib/crazyswarm/crazyswarm_server __name:=crazyswarm_server __log:=/home/porthos/.ros/log/be87f40e-5aae-11e8-8373-e0d55e242924/crazyswarm_server-2.log].
log file: /home/porthos/.ros/log/be87f40e-5aae-11e8-8373-e0d55e242924/crazyswarm_server-2*.log
^C[rviz-5] killing on exit
[crazyswarm_teleop-4] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
```

**Comment by whoenig** [comment]
For the first issue, are you using `./build.sh`? It looks like the crazyflie_cpp submodule was not checked-out correctly, as done in the following lines: https://github.com/USC-ACTLab/crazyswarm/blob/master/build.sh#L7-L10.

For the second issue, you need to install `sudo apt install ros-kinetic-joy`.

**Comment by sarvjeetdh** [comment]
I used this method and getting the same error 

$ mkdir -p ~/crazyflie_ws/src
$ cd ~/crazyflie_ws/src
$ catkin_init_workspace

$ git clone https://github.com/whoenig/crazyflie_ros.git
$ cd ~/crazyflie_ws
$ catkin_make

I have just started with crazyflie and can't locate that ./builld.sh 

Please help

**Comment by whoenig** [comment]
@sarvjeetdh: You seem to use crazyflie_ros only and not the crazyswarm. Please open an issue [here](https://github.com/whoenig/crazyflie_ros/issues) instead.

**Comment by sarvjeetdh** [comment]
Ok... Thanks

**Comment by pPatrickK** [comment]
Hi, 

you were right with the submodule.

Thanks
