### ISSUE TITLE
Installing from 'Flying multiple uavs using ROS' paper

### ISSUE THREAD

**Issue by Pop99** [USC-ACTLab/crazyswarm#67]
Hi,
Trying a couple of installations on different machines, but following the procedure from this document I hit a problem when starting the CF Client on page 7.

![cf_sony](https://user-images.githubusercontent.com/24283106/41254325-159d63b8-6dbb-11e8-83e2-a95a9f0c3dd6.png)

import error no module named cfclient

Any ideas would be appreciated

**Comment by whoenig** [comment]
This has nothing to do with the crazyswarm repository. The specified document is for an older cfclient version and the procedure might have changed in the latest version. I recommend checking the official documentation/forum for help.
