### ISSUE TITLE
Update the libmotioncapture submodule

### ISSUE THREAD

**Issue by shupx** [USC-ACTLab/crazyswarm#712]
The [libmotioncapture](https://github.com/USC-ACTLab/crazyswarm/tree/master/ros_ws/src/crazyswarm/externalDependencies) submodule is still the old one (commit @27cd890). But its original repository has been updated this year to fix some problems and add additional features such as supporting Nokov motion capture system. So this submodule needs update in crazyswarm.

**Comment by whoenig** [comment]
I don't think we can easily update it without testing. And testing is difficult since ROS1/noetic is not supported on Ubuntu 22.04, which I am running. I propose that new users use Crazyswarm2, and old users can update libmotioncapture manually, if they need some of the new features.
