### ISSUE TITLE
How to get IMU data from crazyflie-firmware?

### ISSUE THREAD

**Issue by Rwik2000** [USC-ACTLab/crazyswarm#719]
I want to get real time IMU data from the crazflie-firmware. Is there any method to expose the sensor data from the firmware to the crazyswarm interface?

**Comment by knmcguire** [comment]
You can use the generic logging block functionality.

Just fill in these lines with [the log variables](https://www.bitcraze.io/documentation/repository/crazyflie-firmware/master/api/logs/)  that you want:
https://github.com/USC-ACTLab/crazyswarm/blob/beb05492eaf226462631545bf5972199099267c2/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L11-L13

(probably stateEstimate.roll/pitch/yaw. )

And enable logging with True https://github.com/USC-ACTLab/crazyswarm/blob/beb05492eaf226462631545bf5972199099267c2/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L44

Mind that the roll pitch yaw might already be accessible with the pose logging too.

_Just a note, if you don't have to use ROS1 I would recomment you to go to the ROS2 port of crazyswarm2 as that will be more actively maintained: https://imrclab.github.io/crazyswarm2/_
