### ISSUE TITLE
Crazyswarm 1.0 compatibility with ROS2 Humble?

### ISSUE THREAD

**Issue by Jushan-Randy-Chen** [USC-ACTLab/crazyswarm#726]
Hi,

I am having some weird issues (drones can't stay at hover steadily) after I've upgraded to Crazyswarm 2.0. I wonder if ROS2 Humble is also compatible with Crazyswarm 1? I had no such issues when working with Crazyswarm 1.0 so I wonder if I can just revert back to that version without downgrading my Ubuntu 22.04 and ROS2.

**Comment by whoenig** [comment]
No, since ROS2 is a breaking change over ROS1. Crazyswarm2 is the official successor. Please open an issue in Crazyswarm2 to get help there.

**Comment by knmcguire** [comment]
https://github.com/IMRCLab/crazyswarm2 :slightly_smiling_face:
