### ISSUE TITLE
several crazyswarm problems

### ISSUE THREAD

**Issue by jonesbmj** [USC-ACTLab/crazyswarm#77]
Hello again,

Further along the crazyswarm documentation we are running into more errors when trying to run various sections. Any help you could give would be great.

1. Firmware upgrades for crazyradio: after launching the bootloader, flashing the firmware, and then unplugging and plugging back in. the crazyradio has a green led lit up now but does not show up when we run crazyflie_tools scan.

2. Can you explain the benefits and drawbacks to using motionCapture vs libobjecttracker? I'm a bit lost as to which one to use and what the difference is.

3. We have a vicon system which views the drones, but whenever we launch crazyswarm hover_swarm.launch, rviz launched but is unable to display or find the crazyflies. The error is "No tf data. Actual error:fixed frame [world] does not exist". Additionally whenever we run something like rosrun tf view_frames, there is no tf data. This makes me think there is a problem communicating with our vicon system (which is on a separate pc, but same network). I know this is all vague, but could you recommend any troubleshooting options?

4. Any further detail you could give about the three configuration files would be very helpful. Especially what to add to the "allCrazyflies.yaml" and "crazyflieTypes.yaml". So far I've added an id, channel, initial position, and type for each of our four crazyflies.

Thanks for all your help!

**Comment by whoenig** [comment]
1. That's concerning. Did the verification step succeed? Please run `lsusb` (without and with the Crazyradio plugged in), and find the line for the radio and post it here.

2. motionCapture: VICON will do the tracking. This is the best if you work on a few CFs only (up to 5 perhaps) - each CF will need its unique marker configuration. LibObjectTracker: Use if you have more than 5 CFs with identical marker configuration.

3. Does the ROS package `vicon_bridge` work for you? Can you ping the VICON machine at the hostname/IP you provided? Is there a firewall in between the two PCs?

4. crazyflieTypes.yaml: Groups parameters for CFs that are physically identical. If you only use a standard Crazyflie 2.0, you will only need one entry here (based on the "default" type). If you built custom quads using the bigQuad deck, you might need to add additional types.
allCrazyflies.yaml: List of all CFs that you have with their initial position, id, channel, and type. You can still select/deselect individual CFs using `chooser.py` (which in turn generates crazyflies.yaml that is used internally in the crazyswarm_server, but should not be edited manually).

**Comment by YimingWan** [comment]
Hello, 
We have a quick question regarding changing the IP for now.  Vicon_bridge does work for us separately and we were able to connect before using the earlier crazyflie documentation. Under vicon_bridge their was a launch file (vicon.launch) where we could adjust the IP to match the host computer. We are not sure where under crazyswarm we can change the IP to do the same or if its already connected.

Thank you again for your time and help!

**Comment by whoenig** [comment]
You can change the hostname (or IP) here: https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L43. The Crazyswarm uses (like vicon_bridge) the VICON DataStream SDK directly.

**Comment by YimingWan** [comment]
Hi whoenig,
Sorry to bother you again, we change the IP successfully, after we run the roslaunch crazyswarm hover_swarm.launch, we can see the vicon dots on the rviz command window but Global status shows warning, it says that "No tf data. Actual error:Fixed Frame [world] does not exist". And in our command terminal shows "No updated pose for CF cf2", "Initialize did not succeed (fitness too low)". Is there anyway to fix this problem?

Thanks again for your time and help!
![screenshot from 2018-06-27 15-08-08](https://user-images.githubusercontent.com/14075700/41995191-dc47e3f2-7a1e-11e8-9f6c-baf9bcd5f947.png)
![screenshot from 2018-06-27 15-29-07](https://user-images.githubusercontent.com/14075700/41995193-df1e6402-7a1e-11e8-90de-a5e883a63f47.png)

**Comment by whoenig** [comment]
You will need to update the configuration files if you use libobjecttracker, see http://crazyswarm.readthedocs.io/en/latest/usage.html#configure-marker-arrangement for a list of steps.

**Comment by YimingWan** [comment]
Hi Whoenig,
I'm so sorry to bother you again, follow your comment I updated the configuration files, but when I run the  roslaunch crazyswarm hover_swarm.launch, the "[crazyswarm_server-2] process has died [pid 7261, exit code -11" error shows up; and on the rviz command window it also shows "No tf data. Actual error:Fixed Frame [world] does not exist."  We thought it might be the problem in the communication between the motion capture system and the Crazyswarm server, how could we fix that? 
Thanks again for your time and help!
![screenshot from 2018-06-28 12-06-49](https://user-images.githubusercontent.com/14075700/42046735-821693ac-7acc-11e8-9f3d-48a9f4c6f693.png)
![screenshot from 2018-06-28 12-07-07](https://user-images.githubusercontent.com/14075700/42046741-85303188-7acc-11e8-8f5c-2b11d5846177.png)

**Comment by whoenig** [comment]
This means that there is a segfault in the server, probably because of some issues in the config files (although additional error checks in there should actually catch most obvious mistakes with a more meaningful message). In case of communication issues, no segfault should occur. Make sure you actually used floating point numbers (e.g., "0.0" instead of "0").

Do debug/find out what the issue is, please follow the steps in my first comment here: https://github.com/USC-ACTLab/crazyswarm/issues/68.

Thanks!

**Comment by YimingWan** [comment]
Hi whoenig,
Sorry to bother you again, we got a very confused problem. We run figure8_csv.py this afternoon, everything is good, drones fly perfect. But an hour later when we try to rerun the figure8_csv.py, it shows ImportError: No module named crazyflie_driver.srv. This problem looks little bit tricky, so we ask you for some help. Thanks for your time and help!
![screenshot from 2018-06-29 17-12-55](https://user-images.githubusercontent.com/14075700/42115195-ee4cf8ba-7bbf-11e8-8e8e-f886d926854e.png)

**Comment by whoenig** [comment]
You'll need to source your ros workspace. If you are in the folder from the screenshot, you can do so by executing `source ../../../devel/setup.bash`.
