### ISSUE TITLE
"Motion Capture did not receive data" issue

### ISSUE THREAD

**Issue by woolinjung** [USC-ACTLab/crazyswarm#772]
I keep getting this issue when I run the "ros2 launch crazyflie launch.py" script which was in the crazyswarm2 tutorial.
We are using motion capture via Vicon and it is connected to it, but I keep getting the following error. We have configured Vicon with an object titled "cf1" and our crazflies.yaml includes "cf1" with the right radio address. Also, there is no data streaming in the "poses" topic. Thanks for the help in advance!

![Screenshot from 2023-10-31 21-12-08](https://github.com/USC-ACTLab/crazyswarm/assets/143849294/c163c159-5ae2-451c-8646-b36ea1866eef)

**Comment by whoenig** [comment]
This is for Crayzswarm2, not 1.
