### ISSUE TITLE
Position Feedback from Crazyflie 2.0

### ISSUE THREAD

**Issue by YimingWan** [USC-ACTLab/crazyswarm#80]
I would like to get position feedback from the crazyflie while its moving to the waypoints in waypoints.csv. Is there any way to achieve this?

**Comment by whoenig** [comment]
You can enable logging https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L53, and a list of variables (e.g. https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L19). The variables you want are probably stateEstimate.{x,y,z}.
