### ISSUE TITLE
crazyswarm Pointcloud issues

### ISSUE THREAD

**Issue by txlin** [USC-ACTLab/crazyswarm#9]
We're currently in the process of trying to run the crazyswarm stack but we're hitting a few issues. When we run hover_swarm.launch no pointcloud and no tf data is available. 

A potential issue we thought of is that we're running vicon tracker on a separate computer in the network so we thought vicon_host_name: was meant for the ip address but when changing it we get a std::runtime_error. 

It seems like we've followed the setup and documentation appropriately, is there something else we're missing in setup?

**Comment by whoenig** [comment]
Did you follow the documentation on readthedocs (http://crazyswarm.readthedocs.io/en/latest/). What you are describing sounds indeed like a communication issue. The typical setup is to have two machines, one Windows and one Linux box on the same network. You can try your setup with the vicon_bridge package (https://github.com/ethz-asl/vicon_bridge). Also make sure that the ports are open (disable the firewall on your windows box) and that you can ping the vicon machine from the linux box.

**Comment by vss2sn** [comment]
We've checked the setup by pinging the host machine and using Vicon bridge. Is there some place we could specify the IP address of the host machine?

**Comment by jpreiss** [comment]
@txlin @vss2sn I am trying to close dead issues. Is your Vicon communication working properly now?
