### ISSUE TITLE
Errors when using Linux 18.04 and ROS Melodic

### ISSUE THREAD

**Issue by The-SS** [USC-ACTLab/crazyswarm#90]
Hi,

I know this package is intended for Linux 16.04 and ROS Kinetic, but I thought of trying to build it on Linux 18.04 LTS and ROS Melodic.

When building the latest commit (78bcb6b), I was stopped by the following error:
```
crazyswarm/ros_ws/src/externalDependencies/libmotioncapture/externalDependencies/Qualisys2Ros/include/RTProtocol.cpp:451:54: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
                 if (ReceiveRTPacket(eType, false) == false)
``` 
Since I am using VICON, I simply replaced this check with `if (false)` (because I don't care whether or not Qualisys works) and tried rebuilding. The package then built normally. If this issue is tended to, or if users are given the option of whether or not they want the Qualisys2Ros package, I think the Crazyswarm package would be able to support Linux 18.04 and ROS melodic as is.

Another thing to note is that older versions of this package did not use the `functional` header (`#include <functional>`) when `std::function` was used in the `crazyflie_ros` package. This is not an issue on Linux 16.04 with gcc/g++ 5.4, but with Linux 18.04 and gcc/g++ 7.3, not having the `functional` header will throw an error. So, for those planning to use an older version of Crazyswarm with Linux 18.04, you might want to add that header to cpp files that use `std::function`.

**Comment by jpreiss** [comment]
can you make a pull request with the fixed `#include<functional>` ?

**Comment by The-SS** [comment]
The current version of the Crazyswarm package does not suffer from the `#include <functional>` issue (the crazyflie_ros package used contains that header). 

But, the older version of that package that I was trying to compile [crazyswarm at commit 209](https://github.com/USC-ACTLab/crazyswarm/tree/fba417a6035023322eccf855cc997f6244534479) had that issue. Can/should I create a pull request based on crazyswarm commit 209? That commit is almost a year old.

**Comment by The-SS** [comment]
#### An update about using the Crazyswarm package (commit 273) with Linux 18.04:
Aside from the Qualisys issue above, the package builds `crazyswarm` and `crazyflie-ros`. Crazyswarm scripts that start the swarm and issue `goTo` commands, as well as others, work properly. I also [added full_state commands](https://github.com/The-SS/crazyswarm/tree/025d1ae7268ed36b85c6590968854bb79f9dd4d6) and those work fine (in a certain way).
A new problem that I discovered is that `crazyflie-firmware` and `crazyfie2-nrf-firmware` do not compile properly due to a problem with the arm cross-compiler on Linux 18.04. (This can be resolved using a virtual machine).
I'm closing the issue for now, but I'll post any additional problems when using Linux 18.04 (potentially with solutions or workarounds).
