### ISSUE TITLE
Drone takes off towards wrong directions

### ISSUE THREAD

**Issue by jchen93nj** [USC-ACTLab/crazyswarm#96]
Hi there,

I am trying to fly a single crazyflie 2.0 under qualisys motion capture system. However the drone cannot take off correctly. Here are the steps I took:

1. Put drone at the world frame origin. Launch mocap_helper.launch and get positions of the four markers. Copy the initial positions and paste on crazyflieType.yaml with offset (0.0, 0.0, 0.0).
2. Launch server (hover_swarm.launch). I could see rviz showing the world and cf frames overlapping with each other.
3. Launch individual_hover.py (or other script).

What happens most is that instead of going upward and hovering, the drone flies to a certain direction and stops after crashing (before I hit Enter and continue the next action which is landing). The direction may vary but the drone can never go upward and maintain steady. 

Do you have any ideas about the issue? Thanks a lot.

**Comment by whoenig** [comment]
Thanks for the update! I am at a conference, so sorry for the delay. Closing.
