### ISSUE TITLE
vicon connection issues and directory confusion

### ISSUE THREAD

**Issue by pete9936** [USC-ACTLab/crazyswarm#98]
Hi,
I believe I have a connection issue between Vicon and crazyswarm. When I run hover_swarm I have not been able to see any cf on rviz. A similar concern was brought up in Issue #37 but I think something else may be occurring here. 

I am successfully able to run the crazyflie_ros > crazyflie_demo files using the vicon_bridge that you outlined in your previous work. For this I am connecting to vicon over our remote network as opposed to locally with an ethernet connection but that shouldn't be an issue. 

I also noticed in Issue #29 that some pieces with the vicon installation have maybe recently changed. I followed what was done there and downloaded DataStreamSDK 1.7 and placed it in the directory specified `ros_ws/src/crazyflie_ros/externalDependencies/libmotioncapture/externalDependencies/vicon_sdk ` but had some confusion here. It seems that on this path you have already added `vicon-datastream-sdk`. The vicon_sdk structure I have is as follows:
![vicon_sdk_tree](https://user-images.githubusercontent.com/31454586/46549292-17389080-c897-11e8-9f80-fdcb14f2419a.png)
Where just a portion of the vicon-datastream-sdk that you have prebuilt is:
![vicon-datastream-sdk_tree](https://user-images.githubusercontent.com/31454586/46549329-3c2d0380-c897-11e8-846c-fb2343039434.png)
I was wondering have you recently changed things and added all of this? I haven't seen anyone bring it up. Would it be alright to just delete the `vicon-datastream-sdk` that is preloaded and simply use my 'vicon_sdk' directory? Or are there may changes that would need to be made?

Following off that, I moved forward anyway and as you suggested in #37 I changed the hostname (`vicon`) to the IP address of our network when trying to run `hover_swarm.launch` by changing hostname in `crazyswarm_server.cpp` as follows:
![crazyswarm_server_cpp_ipsnip](https://user-images.githubusercontent.com/31454586/46550206-f1f95180-c899-11e8-9283-f106536fbba6.png)
And also tried this for `mocap_helper.launch` by modifying `mocap_helper.cpp` as follows:
![mocap_helper_cpp_ipsnip](https://user-images.githubusercontent.com/31454586/46550252-1f45ff80-c89a-11e8-8fca-61377166f6c9.png)
And when I run this as detailed in the [Configure Marker Arrangement](https://crazyswarm.readthedocs.io/en/latest/usage.html#configure-marker-arrangement) section I get no output.
Just to be thorough, while attempting to run `hover_swarm.launch` I chose to use `motionCapture` as the `object_tracking_type` and had "track" enabled for my objects cf1 and cf2 with the proper uri convention specified. And when I ran `mocap_helper.launch` I was ceratin to change the object_tracking_type to `libobjecttracker` and not to have "track" enabled on the Tracker software. I certainly tried with and without for both.

Am I going about this process correctly? And what could/should I change? And sorry for the long question, just wanted to be thorough.

**Comment by whoenig** [comment]
VICON recently published the SDK as open source, so there is no need anymore in manually putting the SDK (the readthedocs should reflect those changes). 

For your IP address: You should change the address in the launch file and not in the code, i.e., https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/hover_swarm.launch#L43 or https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/launch/mocap_helper.launch#L9. The other things (tracking mode) sound perfectly good to me.

Thanks for the detailed report and please let me know if it works when you specify the IP address in the launch file.

**Comment by pete9936** [comment]
Thank you for getting back so quickly. Yes the process is very simple and straight forward now! The `mocap_helper.launch` works now that I changed the IP address in that file and I am streaming data from Vicon as expected.

However, I made the same modifications in `hover_swarm.launch` and I am getting an output error. I made the modification as you suggested:
![hover_swarm_ipchange](https://user-images.githubusercontent.com/31454586/46561311-af953c00-c8bc-11e8-91db-e8b177aaf438.png)
But for some reason I get an error when I run `roslaunch crazyswarm hover_swarm.launch`
![hover_swarm_error](https://user-images.githubusercontent.com/31454586/46561387-16b2f080-c8bd-11e8-920e-461f411ca678.png)
I'm not sure if it's even associated with the Vicon changes. Rviz shows up but it is empty. For reference I am using Tracker 3.6 to track two crazyflies, cf1 and cf2. With `uri:=radio://0/80/2M/E7E7E7E701` and `uri:=radio://0/80/2M/E7E7E7E702`. I have changed the `allCrazyflies.yaml` file accordingly and sourced the ros_ws into my .bashrc.

Any suggestions?

**Comment by pete9936** [comment]
I went poking around other issues and I found that this has come up a couple of times. It looks like Issue #77 came across a similar vicon issue and solved it the same way. However, they also had the same `process has died   exit code -6` error as described above. 

So I followed that thread which led to debugging using the technique of Issue #68 . This is where I'm now stuck. So I did the following like you said:
`$cd ros_ws
$rm -rf build/ devel/
$catkin_make -DCMAKE_BUILD_TYPE=Debug`
And then updated the `hover_swarm.launch` file with the debugging launch prefix:
![hover_swarm_debug_launch_prefix](https://user-images.githubusercontent.com/31454586/46563678-87133f00-c8c8-11e8-9f76-4e0e2dc4ed11.png)
Then in gdb I would `run` the node and then use the command `bt` to display the issue. However, I am unable to figure out what is wrong. Here is what I get from gdb:
![gdb_server_node_output](https://user-images.githubusercontent.com/31454586/46563832-541d7b00-c8c9-11e8-8189-a7592d72c5f5.png)

Any ideas moving forward? I think I'm officially stuck for now.

**Comment by pete9936** [comment]
Well, I suppose it looks like the issue is at `crazyswarm_server.cpp` but I have left that completely untouched.

**Comment by whoenig** [comment]
The timeout exception means that the server couldn't connect to one or both CFs. Please double check the URIs and try to connect using the official client.

**Comment by pete9936** [comment]
I looked back in the crazyflies.yaml file and my values were incorrect. Changed that and everything is working very nicely! I can successfully hover both of my Crazyflies!

Thanks so much for helping me out with this, and awesome work on the updated controller. The stability is really solid! 

I will close this issue since all is well.

**Comment by whoenig** [comment]
Awesome, thanks for the update!

**Comment by anikasaraf** [comment]
> I looked back in the crazyflies.yaml file and my values were incorrect. Changed that and everything is working very nicely! I can successfully hover both of my Crazyflies!
> 
> Thanks so much for helping me out with this, and awesome work on the updated controller. The stability is really solid!
> 
> I will close this issue since all is well.

How did you decide what values to put in your crazyflies.yaml
